### ISSUE TITLE
Cannot chain more than one call to a pg_search scope

### ISSUE THREAD

**Issue by pivotal-casebook** [Casecommons/pg_search#1]
````
ruby-1.8.7-p174 :001 > BlogPost.search("foo").search("bar")
ActiveRecord::StatementInvalid: PGError: ERROR:  ORDER BY "pg_search_rank" is ambiguous
````

**Comment by nertzy** [comment]
#240 introduces a failing spec if anyone wants to try their hands at a fix.

I merged the spec into the [issue-1 branch](https://github.com/Casecommons/pg_search/tree/issue-1).

**Comment by doits** [comment]
Should be possible to overcome this by making `pg_search.rank` unique. The only problem I see is that it is hardcoded in [WithPgSearchRank module](https://github.com/Casecommons/pg_search/blob/bbf62c3f19677819f8a554ea65093ffce8f47df8/lib/pg_search/scope_options.rb#L34), so this would have to be changed first to not use a module like this to extend the scope but something coming from the `ScopeOptions` instance ...

**Comment by budu** [comment]
I've written a fix inspired by @davearonson solution for this issue as I'm currently working on a project with rather complex uses of pg_search in combination with ransack. All tests are passing and I've written two more, based on @nertzy work. The gem behavior should be only minimally affected, enjoy!

More details in the commit message.
