### ISSUE TITLE
Only matching whole words despite setting :using => {:tsearch => {:prefix => true}}

### ISSUE THREAD

**Issue by snoblenet** [Casecommons/pg_search#102]
I have a Reference model:

```
class Reference < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:source_text, :citation], :using => {:tsearch => {:prefix => true}, :ignoring => :accent}
end
```

A 9.x version of postgres:

```
$ psql --version
psql (PostgreSQL) 9.2.2
```

And a rebuilt index:

```
pry(main)> PgSearch::Multisearch.rebuild(Reference)
```

When I search on whole words, like "lorem ipsum", I get search results, but when I search on partial words, like "lore", I get no results. Why? And how can I fix this?

**Comment by pupeno** [comment]
Is this still true in 2024?
