### ISSUE TITLE
Error: PG::Error: ERROR:  column "pg_search_rank" does not exist

### ISSUE THREAD

**Issue by gregolsen** [Casecommons/pg_search#110]
pg_search 0.6.1 fails to build a query when includes used and dot is present in the string

My model config:

    pg_search_scope :full_text_search,
                    against: :content,
                    using: { tsearch: {prefix: true} }

Query:

    Message.full_text_search("to@domain.com").includes(:recipients)

Error:

    Error: PG::Error: ERROR:  column "pg_search_rank" does not exist

Looks like this bug was present before and was fixed #14

**Comment by nertzy** [comment]
Closing this because pg_search 1.0 uses a different strategy to build the query. Please open a new issue if you have problems going forward.

**Comment by hallmatt** [comment]
I've upgraded to 1.x and am still getting this issue. At first I thought it was related to large results being returned, but I have an example where only one result is returned. Here's the full line of code I'm using:

`search(keywords).reorder('pg_search_rank DESC')`

If I walk through the issue with a debugger, I can get one result using the search function:

`
search(keywords)
`

but as soon as I tack on the reorder function, I get a hard crash

`search(keywords).reorder('pg_search_rank DESC')`

`
INTERNAL ERROR!!! PG::UndefinedColumn: ERROR:  column "pg_search_rank" does not exist
LINE 1: ...arch_id WHERE "machines"."tenant_id" = 1 ORDER BY pg_search_...
`

**Comment by hallmatt** [comment]
It looks like it works fine with multisearch, but not on the individual model search

Individual Model Search Options:

```
  pg_search_scope :search,
                  :against => [:model_description, :stock_order_number, :serial_number, :year, :hours, :total_price, :stick_length, :pad_width, :transmission_type, :tires, :attachments, :two_or_four_wheel_drive, :bucket_size, :other, :cab2_rops, :app_weight, :comments, :description, :category_name, :make_name, :notes],
 :using => {
              :tsearch => {
                :prefix => true,  # otherwise only matches whole words
                :dictionary => "english"  # enables 'stemming' features e.g. jump, jumped, jumper
              },
              :trigram => {:threshold => 0.3}
            }
```

Multisearch Options
```
PgSearch.multisearch_options = {
  :using => {
              :tsearch => {
                :prefix => true,  # otherwise only matches whole words
                :dictionary => "english"  # enables 'stemming' features e.g. jump, jumped, jumper
              },
              :trigram => {:threshold => 0.3}
            }
            
}                 
```
