### ISSUE TITLE
tsvector column on model combined with association searches?

### ISSUE THREAD

**Issue by uberllama** [Casecommons/pg_search#122]
Hi folks. I have a tsvector column on my users table with an upsert trigger that combines several searchable elements (name, email, description). In my application, a user belongs to an organization, so I'd also like to search users by organization name. Has anyone successfully handled association searching through a tsvector column, or managed to use an existing tsvector column along with associated searches? Cheers.

**Comment by roberts-n** [comment]
Would it be possible to use something like this with gem globalize?
