### ISSUE TITLE
PGError: ERROR: operator does not exist: text % unknown

### ISSUE THREAD

**Issue by ghost** [Casecommons/pg_search#123]
Running into this again.Yes, pg_trgm is installed. 

  `pg_search_scope :search, :against => :title, :using => [:tsearch, :trigram]
      company.positions.search("CUSTOMER SERVICE ASSOCIATE")`

`PG::Error: ERROR:  operator does not exist: text % unknown
LINE 1: ...))) OR ((coalesce("positions"."title"::text, '')) % 'CUSTOME...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT "positions".*, ((ts_rank((to_tsvector('simple', coalesce("positions"."title"::text, ''))), (to_tsquery('simple', ''' ' || 'CUSTOMER' || ' ''') && to_tsquery('simple', ''' ' || 'SERVICE' || ' ''') && to_tsquery('simple', ''' ' || 'ASSOCIATE' || ' ''')), 0))) AS pg_search_rank FROM "positions"  WHERE "positions"."company_id" = 37 AND (((to_tsvector('simple', coalesce("positions"."title"::text, ''))) @@ (to_tsquery('simple', ''' ' || 'CUSTOMER' || ' ''') && to_tsquery('simple', ''' ' || 'SERVICE' || ' ''') && to_tsquery('simple', ''' ' || 'ASSOCIATE' || ' '''))) OR ((coalesce("positions"."title"::text, '')) % 'CUSTOMER SERVICE ASSOCIATE')) ORDER BY pg_search_rank DESC, "positions"."id" ASC`

pg_search 0.6.4
Rails 3.2.13
postgres 9.2.4.1

**Comment by mibamur** [comment]
@balancedcomp hello
how you solved it?

**Comment by u007** [comment]
makesure you have trigram installed
```
CREATE EXTENSION pg_trgm
```
