### ISSUE TITLE
Dynmically sort/order results from query raises error

### ISSUE THREAD

**Issue by thoughtpunch** [Casecommons/pg_search#129]
I'd like to be able to SQL order a collection of results by an associated column (just like any other ActiveRecord::Relation). The search results are presented in a table where the user can sort/filter dynamically, so maintaining the default rank sort is not a priority.

I'd like to be able to do something like this:

``` ruby
class Unicorn
   has_many :rainbows

   pg_search_scope :search_by_awesomeness,
     :against => [:awesomeness],
     :associated_against => {:rainbow => [:color]}
end

class Rainbow
   belongs_to :unicorn
end

Unicorns.search_by_awesomeness("off the charts").order("rainbow.color")
```

However, when I try to chain a `order` onto a result collection I get the following error:

```
PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "rainbow"
```

I've tried including and joining the associated table, both before and after the query, but no dice.

I saw the semi-solution of defining a tie-breaker `:order_within_Rank` as in https://github.com/Casecommons/pg_search/issues/22, but this won't work for me as I need to be able to dynamically sort the results.

Any ideas?

**Comment by ianaverno** [comment]
This issue shouldn't be closed just because reorder works if you are ordering by a model's fields.
It still doesn't work when you try to order by its associations. `.references()` doesn't solve it for `.includes()`. Apparently, pg_search_scope is generating a query, which for some reason doesn't chain well with complex queries in rails.

**Comment by kartikupadhyay90** [comment]
Also facing the same issue

**Comment by stephendolan** [comment]
Same issue just cropped up for me. Ordering by an association just doesn't work with `includes`, which is what the popular `bullet` gem requests for eager loading.

**Comment by ipcross** [comment]
Doesn't work with includes for me too.

**Comment by mguidetti** [comment]
Having this problem as well

**Comment by lcampanari** [comment]
This ticket should be reopened as the problem still happens when trying to order by an association.
