### ISSUE TITLE
Speeding up queries that use associations

### ISSUE THREAD

**Issue by digitalheir** [Casecommons/pg_search#130]
Hi,

Thanks so much for this great gem. I have one issue with it, though. In the manual, it says:

>## Searching through associations
It is possible to search columns on associated models. Note that if you do this, it will be impossible to speed up searches with database indexes. However, it is supported as a quick way to try out cross-model searching.

The last lines seems to suggest that this is a good way to prototype searching through associations, but is there a way to it so that I can have cross-model searching, and it is fast at the same time?

**Comment by nertzy** [comment]
Closing this for now. I would gladly accept a pull request that introduces a more performant way to do association searches.. Until then, please try the workarounds mentioned above.

**Comment by kesha-antonov** [comment]
@monfresh Thanks for the link! It helped me.

And @nertzy thanks for the awesome gem!

**Comment by cmalpeli** [comment]
@monfresh that link no longer works - can you reshare?

**Comment by monfresh** [comment]
@cmalpeli That wasn't my blog post, so I can't reshare that particular link, but you can take a look at my project to see how to implement a `tsvector` column for searching across tables: https://github.com/codeforamerica/ohana-api/blob/master/db/migrate/20140508194831_update_search_vector_migration.rb

and how to use it in the app: https://github.com/codeforamerica/ohana-api/blob/master/app/models/concerns/search.rb#L29-L40

Note that `pg_search` is not required to be able to do this.

**Comment by cmalpeli** [comment]
Very nice - thank you!

**Comment by raoulalwani** [comment]
Adding a wayback link to the article @monfresh posted previously, might be helpful to others who come across this:

https://web.archive.org/web/20150329002818/http://altoros.github.io/2013/implementing-and-improving-postgresql-fulltext-search/
