### ISSUE TITLE
Allow disabling of automatic multi-search indexing on a per-object basis

### ISSUE THREAD

**Issue by dlikhten** [Casecommons/pg_search#133]
The work to index a multisearch record for a single record may take a while especially if it is indexing dependency objects. It would be extremely helpful to be able to disable automated indexing in favor of a cron job that does the work say every 10 minutes for the updated records.

My proposal is to add a option to multisearch: `multisearch disable_auto_indexing: true`

This, combined with the ability to execute: `record.update_pg_search_document` will make the need fully solved.

**Comment by nertzy** [comment]
You can now pass an `update_if: -> {}` lambda to `multisearchable` to control whether the record is updated.
