### ISSUE TITLE
How to add indexes

### ISSUE THREAD

**Issue by tcocca** [Casecommons/pg_search#15]
So I have a model, Property, and I want to use a simple search_scope:

``` ruby
class Property < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_keywords, :against => :description
end
```

I opened script/console and did a simple: `Property.search_by_keywords('test')`  and it generated the following query:

``` sql
SELECT "properties".*, (ts_rank((to_tsvector(E'simple', coalesce("properties"."description", ''))), (to_tsquery(E'simple', E''' ' || E'test' || E' ''')))) AS pg_search_rank FROM "properties"   WHERE (((to_tsvector(E'simple', coalesce("properties"."description", ''))) @@ (to_tsquery(E'simple', E''' ' || E'test' || E' '''))))  ORDER BY pg_search_rank DESC, "properties"."id" ASC
```

How would I go about adding a fulltext index for this search scope so that the query is fast.

Keep in mind eventually I will want to do something like:

``` ruby
Property.search_by_keywords('town house').paginate(:conditions => {:state => 'MA', :price => (0..250000)}, :order => "price asc", :page => 1, :per_page => 25)
```

Or you get the point, we are going to be combining the search_scope for keywords with some other complex filtering.  Any ideas on what the best index syntax is to use to add the index on the fulltext for description?

~ Tom

**Comment by cmalpeli** [comment]
@jaimeiniesta this is great - thanks for sharing!  how would the syntax on your migration look for multiple columns?  would you need one trigger for each column?

**Comment by kelso** [comment]
@jaimeiniesta and the solution can be complete if you know how to setup indexes while using multisearchable approach.
Because multisearch looking for `tsv_body` in table `pg_search_documents` instead of just `posts`: :tired_face: 

ActiveRecord::StatementInvalid in SearchResults#index
`PG::UndefinedColumn: ERROR:  column pg_search_documents.tsv_body does not exist`

**Comment by Cgipson06** [comment]
@cmalpeli To use that approach with multiple columns, all the columns can be listing inside of the calls for [coalesce](https://www.postgresql.org/docs/9.4/static/functions-conditional.html) and [ts_vector_update_trigger](https://www.postgresql.org/docs/9.4/static/textsearch-features.html).  To search the Post body, title, and author
```ruby
# Updates existing rows so this new column gets calculated
execute <<-SQL
  UPDATE posts SET tsv_body = (to_tsvector('english', coalesce(body,title,author, '')));
SQL
    
# Sets up a trigger to update this new column on inserts and updates
execute <<-SQL
  CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
  ON posts FOR EACH ROW EXECUTE PROCEDURE
  tsvector_update_trigger(tsv_body, 'pg_catalog.english', body,title,author);
SQL
```
