### ISSUE TITLE
RSPec issues with dmetaphone

### ISSUE THREAD

**Issue by pedantix** [Casecommons/pg_search#175]
I am not sure if this is my fault with my rspec setup and/or if it is an issue with rails 4 new replacement of 'rake db:test:prepare', but I am having isssues getting :dmetaphone to work in rspec but not rails console/dev. The error I get is as follows: 

```
PG::UndefinedFunction: ERROR:  function pg_search_dmetaphone(text) does not exist
LINE 1: ...text, '')) % 'action') OR ((to_tsvector('simple', pg_search_...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT "traits".*, ((ts_rank((to_tsvector('simple', coalesce("traits"."trait_name"::text, ''))), (to_tsquery('simple', ''' ' || 'action' || ' ''')), 0))) AS pg_search_rank FROM "traits"  WHERE (((to_tsvector('simple', coalesce("traits"."trait_name"::text, ''))) @@ (to_tsquery('simple', ''' ' || 'action' || ' '''))) OR ((coalesce("traits"."trait_name"::text, '')) % 'action') OR ((to_tsvector('simple', pg_search_dmetaphone(coalesce("traits"."trait_name"::text, '')))) @@ (to_tsquery('simple', ''' ' || pg_search_dmetaphone('action') || ' '''))))  ORDER BY pg_search_rank DESC, "traits"."id" ASC
```

I do not know what is causing this and after 2 hours of trying to figure out why, 'one of these things is not like another', I am reaching out for help. Any insight as to why this is not working would be vastly appreciated.

**Comment by Pitometsu** [comment]
```ruby
config.active_record.schema_format = :sql
```
Is it still necessary? According to [wiki](https://github.com/Casecommons/pg_search/wiki/Installing-Postgres-Contrib-Modules),

> For Rails 4 and higher, this is not required as the following will be added to the schema.rb automatically:
> 
> ```ruby
> # These are extensions that must be enabled in order to support this database
> enable_extension "plpgsql"
> enable_extension "pg_trgm"
> ```

But I have **Rails 4.2.5** and exactly same issue.

**Comment by Pitometsu** [comment]
...And migration to `:sql` not helped me. Sorry if I doing something wrong, still yet so n00b in Rails.

Here what I wave
```
 rake db:migrate:status

database: igor_kurinnoyi_challenge_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   . . .
   up     20160513205904  Add contrib extensions
   up     20160513224341  Add pg search dmetaphone support functions
```
```ruby
class User < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_login, against: [:name, :email],
                                    using: [:trigram, :dmetaphone],
                                    ignoring: [:accents]
end
```
```ruby
class AddContribExtensions < ActiveRecord::Migration
  def change
    enable_extension 'pg_trgm'
    enable_extension 'fuzzystrmatch'
  end
end
```
```ruby
# auto-generated
class AddPgSearchDmetaphoneSupportFunctions < ActiveRecord::Migration
  def self.up
    say_with_time("Adding support functions for pg_search :dmetaphone") do
      if ActiveRecord::Base.connection.send(:postgresql_version) < 80400
        execute <<-'SQL'
CREATE OR REPLACE FUNCTION unnest(anyarray)
  RETURNS SETOF anyelement AS
$BODY$
SELECT $1[i] FROM
    generate_series(array_lower($1,1),
                    array_upper($1,1)) i;
$BODY$
  LANGUAGE 'sql' IMMUTABLE
        SQL
      end

      execute <<-'SQL'
CREATE OR REPLACE FUNCTION pg_search_dmetaphone(text) RETURNS text LANGUAGE SQL IMMUTABLE STRICT AS $function$
  SELECT array_to_string(ARRAY(SELECT dmetaphone(unnest(regexp_split_to_array($1, E'\\s+')))), ' ')
$function$;
      SQL
    end
  end

  def self.down
    say_with_time("Dropping support functions for pg_search :dmetaphone") do
      execute <<-'SQL'
DROP FUNCTION pg_search_dmetaphone(text);
      SQL

      if ActiveRecord::Base.connection.send(:postgresql_version) < 80400
        execute <<-'SQL'
DROP FUNCTION unnest(anyarray);
        SQL
      end
    end
  end
end
```

**Comment by Pitometsu** [comment]
And only after @pedantix 's "Fix" it work in console.

**Comment by Pitometsu** [comment]
With only
```ruby
using: [:trigram]
```
work. But none of this:
```ruby
using: [:dmetaphone]
```
or
```ruby
ignoring: [:accents]
```

**Comment by zeiv** [comment]
Getting this issue in Rails 5, although everything was fine yesterday.... adding the `schema_format` config doesn't help.  Any ideas?  I can verify the extensions have been successfully created in the test database.

**Comment by JomaMinoza** [comment]
@zeiv I am having this error also in Rails 5.
I tried the following steps, it seems working now.

1. Run `rails g migration  InstallFuzzystrmatch`

`class InstallFuzzystrmatch < ActiveRecord::Migration[5.0]
  def self.up
    ActiveRecord::Base.connection.execute("CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;")
  end

  def self.down
    ActiveRecord::Base.connection.execute("DROP EXTENSION fuzzystrmatch;")
  end
end
`

2. Run `rails g pg_search:migration:dmetaphone`

It generates

`class AddPgSearchDmetaphoneSupportFunctions < ActiveRecord::Migration
  def self.up
    say_with_time("Adding support functions for pg_search :dmetaphone") do
      if ActiveRecord::Base.connection.send(:postgresql_version) < 80400
        execute <<-'SQL'
CREATE OR REPLACE FUNCTION unnest(anyarray)
  RETURNS SETOF anyelement AS
$BODY$
SELECT $1[i] FROM
    generate_series(array_lower($1,1),
                    array_upper($1,1)) i;
$BODY$
  LANGUAGE 'sql' IMMUTABLE
        SQL
      end

      execute <<-'SQL'
CREATE OR REPLACE FUNCTION pg_search_dmetaphone(text) RETURNS text LANGUAGE SQL IMMUTABLE STRICT AS $function$
  SELECT array_to_string(ARRAY(SELECT dmetaphone(unnest(regexp_split_to_array($1, E'\\s+')))), ' ')
$function$;
      SQL
    end
  end

  def self.down
    say_with_time("Dropping support functions for pg_search :dmetaphone") do
      execute <<-'SQL'
DROP FUNCTION pg_search_dmetaphone(text);
      SQL

      if ActiveRecord::Base.connection.send(:postgresql_version) < 80400
        execute <<-'SQL'
DROP FUNCTION unnest(anyarray);
        SQL
      end
    end
  end
end
`

3. Then `rails db:migrate`

Hope it solves your problem also. :)

**Comment by JomaMinoza** [comment]
@zeiv I am having this error also in Rails 5.
I tried the following steps, it seems working now.

1. Run `rails g migration  InstallFuzzystrmatch`

```
class InstallFuzzystrmatch < ActiveRecord::Migration[5.0]
  def self.up
    ActiveRecord::Base.connection.execute("CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;")
  end

  def self.down
    ActiveRecord::Base.connection.execute("DROP EXTENSION fuzzystrmatch;")
  end
end

```

2. Run `rails g pg_search:migration:dmetaphone`

It generates

```
class AddPgSearchDmetaphoneSupportFunctions < ActiveRecord::Migration
  def self.up
    say_with_time("Adding support functions for pg_search :dmetaphone") do
      if ActiveRecord::Base.connection.send(:postgresql_version) < 80400
        execute <<-'SQL'
CREATE OR REPLACE FUNCTION unnest(anyarray)
  RETURNS SETOF anyelement AS
$BODY$
SELECT $1[i] FROM
    generate_series(array_lower($1,1),
                    array_upper($1,1)) i;
$BODY$
  LANGUAGE 'sql' IMMUTABLE
        SQL
      end

      execute <<-'SQL'
CREATE OR REPLACE FUNCTION pg_search_dmetaphone(text) RETURNS text LANGUAGE SQL IMMUTABLE STRICT AS $function$
  SELECT array_to_string(ARRAY(SELECT dmetaphone(unnest(regexp_split_to_array($1, E'\\s+')))), ' ')
$function$;
      SQL
    end
  end

  def self.down
    say_with_time("Dropping support functions for pg_search :dmetaphone") do
      execute <<-'SQL'
DROP FUNCTION pg_search_dmetaphone(text);
      SQL

      if ActiveRecord::Base.connection.send(:postgresql_version) < 80400
        execute <<-'SQL'
DROP FUNCTION unnest(anyarray);
        SQL
      end
    end
  end
end


```
3. Then `rails db:migrate`

Hope it solves your problem also. :)

**Comment by sgriff44** [comment]
Excellent, this solved my problem, thanks for the tip: `rails g pg_search:migration:dmetaphone`
