### ISSUE TITLE
Can't find alphanumeric string with hyphens

### ISSUE THREAD

**Issue by johnkelly** [Casecommons/pg_search#19]
In the model:

``` ruby
pg_search_scope :search_by_code,
                  :against => [:code],
                  :using => {
                      :tsearch => {:prefix => true}
                  }
```

Searching for this specific string returns no results: SS-JF-09-11
Everything else works perfectly.

Oddly, since this methods has prefix true, SS-JF-09- will return the correct record.  I double checked the database and the record is entered correctly and this search is working for other strings.

**Comment by sirtaylor88** [comment]
Problem with query started with a number #425
