### ISSUE TITLE
Case insensitive search?

### ISSUE THREAD

**Issue by RickCarlino** [Casecommons/pg_search#196]
## Problem

I have data that was imported from an external source with inconsistent capitalization. Searching in lowercase does not return the intented results. Eg: 'sno' returns 'snow' but not 'Snow'.

``` ruby
class Tag < ActiveRecord::Base
  include PgSearch
  pg_search_scope :autocomplete, against: :name,
                                 using: {tsearch: {prefix: true}}
end
```
## Question

Is there a setting I can add to my search scope to make it case insensitive without needing to add AR validations / normalize the attributes being searched through?

Thanks for maintaining this project. It's been very helpful.

**Comment by sandelius** [comment]
what's the status on this. I'm having the same problem

**Comment by asiniy** [comment]
Have the same problem too

**Comment by nertzy** [comment]
@asiniy Are you using the Russian dictionary? Like this:

```ruby
class Tag < ActiveRecord::Base
  include PgSearch
  pg_search_scope :autocomplete, 
    against: :name,
    using: {
      tsearch: {
        dictionary: 'russian',
        prefix: true
      }
    }
end
```

See http://www.postgresql.org/docs/current/static/textsearch-dictionaries.html for more information. As for whether or not the search is insensitive, that's really up to what PostgreSQL full-text-search does under the hood. pg_search for the most part just forms the queries for you. If there is an option to change the queries generated to choose whether case is insensitive or not, that would be something great to add to pg_search, but otherwise that might be something that you'd need to configure directly with the database.

**Comment by asiniy** [comment]
@nertzy here is mine scope.

``` ruby
  pg_search_scope :search, against: { title: 'A', description: 'B' },
    using: { tsearch: { prefix: true, dictionary: 'russian' } }
```

``` ruby
Task.search('Фасад') # => return records
Task.search('фасад') # => hasn't any record. 'фасад' is undersored 'Фасад'
```

**Comment by ehlyzov** [comment]
Make sure that you have configured collation and ctype correctly. Type `\l+` in psql console and run something like `SELECT LOWER('Фасад')` If `LOWER` doesn't produce the right result you can be sure that it is an enconding issue. In this case, you have to dump your data, create a new database with correct `LC_COLLATION`, `LC_CTYPE` and restore the data.

**Comment by arkdy** [comment]
Just to keep it for future googlers 🧐

Add to `database.yml` `collation` and `ctype` rows as in following example for russian language:

```
default: &default
  adapter: postgresql
  encoding: unicode
  collation: ru_RU.UTF-8
  ctype: ru_RU.UTF-8
```

```

**Comment by nertzy** [comment]
Thanks @arkdy! I'm going to close this issue, since this appears not to be a pg_search issue.

**Comment by msa7** [comment]
By change `database.yml` I got error

```
ActiveRecord::StatementInvalid: PG::InvalidParameterValue: ERROR:  new collation (ru_RU.UTF-8) is incompatible with the collation of the template database (C)
HINT:  Use the same collation as in the template database, or use template0 as template.
```

I have to add `template: template0` rails `database.yml`

```
default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  collation: ru_RU.UTF-8
  ctype: ru_RU.UTF-8
```

Now search works as case insensitive
