### ISSUE TITLE
multisearchable against association fails to rebuild

### ISSUE THREAD

**Issue by joeoftheforsythe** [Casecommons/pg_search#214]
```ruby
class Channel < ActiveRecord::Base
    include PgSearch

    belongs_to :user

    multisearchable against: [:name, :description, :user_name]

    def user_name
        user.name
    end
end
```

When I run `rake pg_search:multisearch:rebuild[Channel]` I get the following error:

```
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column channels.user_name does not exist
LINE 5: ...annels".description::text, '') || ' ' || coalesce("channels"...
```

From the docs, it looks like this should be doable.  Am I missing something?

Thanks!

**Comment by joeoftheforsythe** [comment]
I found a workaround via the comments in this post http://stackoverflow.com/questions/21395704/pg-search-using-a-dynamic-method-as-the-against-parameter

```ruby
multisearchable against: [:name, :description, :user_name], if: ->(x) { true }
```

Not crazy about this, but I guess it's fairly minor

**Comment by nertzy** [comment]
Reopening because this is a legitimate issue. It should work without a workaround.

**Comment by jgrannas** [comment]
I believe this is the same issue as #212 - thanks for looking at this @nertzy

**Comment by amarshall** [comment]
Duplicate of #157
