### ISSUE TITLE
pg_search and globalize - associated_against with translations

### ISSUE THREAD

**Issue by phlegx** [Casecommons/pg_search#216]
Hi!

I want to use ```pg_search``` in combination with gem ```globalize```. How can I search on translated attributes? Here an example:

```ruby
class Project < ActiveRecord::Base
  has_many :tasks

  include PgSearch
  pg_search_scope :search,
                  against: [:name, :description], associated_against: {
                    tasks: {
                      translations: :name
                    }
                  }
end


class Task < ActiveRecord::Base
  belongs_to :project

  translates :name, :description
  globalize_accessors
end
```

The ```task_translations``` table is not included in the sql. Any idea?

**Comment by phlegx** [comment]
I have found a solution that works:

```ruby
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :task_translations, through: :tasks

  include PgSearch
  pg_search_scope :search,
                  against: [:name, :description], associated_against: {
                    task_translations: :name
                 }
end


class Task < ActiveRecord::Base
  belongs_to :project
  has_many :task_translations

  translates :name, :description
  globalize_accessors
end
```

**Comment by amarshall** [comment]
Closing since requester states they solved their problem. Let us know if this is in error.

**Comment by vmarquesdev** [comment]
all globalize association have an translations method use it

```
pg_search_scope :search, against: [:name, :description], associated_against: {
  translations: :name
}
```

**Comment by vmarquesdev** [comment]
You dont need create relation classe, only create relation through translations class
`
class Project < ActiveRecord::Base
  has_many :task_translations, through: :tasks, source: translations

  include PgSearch
  pg_search_scope :search,
                  against: [:name, :description], associated_against: {
                    task_translations: :name
                 }
end
`
