### ISSUE TITLE
minimum character scope

### ISSUE THREAD

**Issue by lfender6445** [Casecommons/pg_search#221]
I'd like to be able to return records, say, on a minimum of 3 characters. Is this possible with pg_search?
 
```
class Toon < ActiveRecord::Base

  include PgSearch

  pg_search_scope :search_by_name, against: :name
end
```
```
Toon.search_by_name 'cow' # => 'cowboy bebop'
```

**Comment by marshall-lee** [comment]
Yes, it will work. What's the problem?

**Comment by lfender6445** [comment]
I am only getting records returned for whole words, in this case 

```
Toon.search_by_name 'cowboy' # => 'cowboy bebop'
```

but

```
Toon.search_by_name 'cow' # => returns empty records

```

**Comment by marshall-lee** [comment]
it's the english language specifics. imagine you google about cows and get results about cowboys :)

**Comment by lfender6445** [comment]
so you mean I  will have better results using 

```
                  :using => {
                    :tsearch => {:dictionary => "english"}
                  }
```

**Comment by nertzy** [comment]
Read about :prefix in the README. 

Grant Hutchins

**Comment by marshall-lee** [comment]
@lfender6445 Yes, it'll be better. Also I'm not sure that "cowboy" must be found by the "cow" query. If you even google for "cow" you won't see cowboys. "cows" — yes, "cowboy" — no.

But if you use pg_search for something like autocomplete feature, you should probably use `:prefix` option as @nertzy said.

**Comment by lfender6445** [comment]
thanks guys will take a look

**Comment by princejoseph** [comment]
@nertzy Is there a way I can specify minimum number of characters for prefix? Right now, it just returns everything.

```ruby
cowboy_bebop = Toon.create!(name: 'cowboy bebop')`

Toon.search_by_name 'cow' # => [cowboy_bebop]
Toon.search_by_name 'co' # => [cowboy_bebop]
Toon.search_by_name 'c' # => [cowboy_bebop]
```
