### ISSUE TITLE
SQL generated by pg_search_scope always coalesces the against columns

### ISSUE THREAD

**Issue by gilbertquri** [Casecommons/pg_search#222]
Why does the SQL generated by pg_search_scope always coalesce the against columns? Wouldn't it defeat the GIN index on these columns?

**Comment by nertzy** [comment]
Not if you also coalesce in your index expression. It's worth revisiting the coalescing for sure, but it's definitely possible to get effective GIN indexes with pg_search.

Grant Hutchins

**Comment by marshall-lee** [comment]
@gilbertquri 
You should add an index for the entire expression generated by pg_search — with all coalesces and concatenations. Expressional indexes can be added using [schema_plus](https://github.com/SchemaPlus/schema_plus_pg_indexes) or with raw sql. You always can ensure that index is really used by running EXPLAIN.

But I advice you to use tsvector column instead to store the result of this expression and add an index on it. It'll also reduce some complexity.

**Comment by gilbertquri** [comment]
Thanks for the tips. Worked like a charm. I don't understand why using tsvector column is less complex though. Don't I need an extra tsvector column for each text column and a trigger to populate each tsvector column?
    _____________________________

**Comment by marshall-lee** [comment]
@gilbertquri 
You need an extra tsvector column for each different pg_search_scope, not for columns.

**Comment by marshall-lee** [comment]
tsvector column would store full-text search data of `against` columns, their weighting, etc.

**Comment by marshall-lee** [comment]
There is also support for multiple tsvector columns #174, but my opinion that in most cases scopes <-> tsvectors should be one-to-one.

**Comment by nertzy** [comment]
Getting back to your original question, I actually can't remember why we coalesce. I believe that there are a few SQL functions that we pass string-ish expressions into that would break otherwise. The easiest way for someone to find out would be to remove the coalesce calls and run the pg_search spec suite and see what happens.

**Comment by nertzy** [comment]
Closing as this isn't really an issue. If someone wants to remove the coalescing and can make a good case for it, I would accept a pull request. Otherwise, coalescing is the default going forward.
