### ISSUE TITLE
pg_scope depends on the order of chaining scopes

### ISSUE THREAD

**Issue by doits** [Casecommons/pg_search#235]
If multiple scopes with joins are chained it can happen that a `pg_scope` does trigger an sql error if not chained first. For example if `search` is a `pg_scope` and `houses_city` is a regular scope which joins a second model:

    Person.search(:some_name).houses_city(:some_city) # works

    Person.houses_city(:some_city).search(:some_name) # triggers an error

I have a test case reproducing this in the following gist: https://gist.github.com/doits/215b3b54496ea47254b8

Second test produces the following exception:

```
PG::UndefinedTable: ERROR:  invalid reference to FROM-clause entry for table "houses"
LINE 1: ...h ON "people"."id" = pg_search.pg_search_id WHERE "houses"."...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "houses_people".
```

My bet is that is has something to do with [table aliasing](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Table+Aliasing), but I am not sure.

Looks like this error is the same as in #229.

**Comment by nertzy** [comment]
I think I've reproduced the error in a143926. I'm trying to figure out if there is a way to introduce `references(:houses)` somewhere into the query to make it work.

Note that in the pg_search spec suite I use my gem [with_model](https://github.com/Casecommons/with_model) which randomizes table names for each spec to make extra sure that we are being careful in constructing queries.

**Comment by doits** [comment]
I think I got it, see my PR #239 - the subquery was modifying the original query. Avoidable by calling `.dup`. But now one other test is failing. I did not have a look at this, maybe it is just a test error?
