### ISSUE TITLE
No results after switching from multi_search to search_scope

### ISSUE THREAD

**Issue by folivi** [Casecommons/pg_search#254]
Hi,
I get no results when searching on a model which was previously mulstisearchable.
Is there any way to tell pg_search to reindex that model?
Cheers

**Comment by nertzy** [comment]
See https://github.com/Casecommons/pg_search#rebuilding-search-documents-for-a-given-class

**Comment by folivi** [comment]
Hi, I've already tried.
```ruby
 PgSearch::Document.delete_all(:searchable_type => "Event")
 Event.find_each { |record| record.update_pg_search_document }
```
output:
NoMethodError: undefined method `update_pg_search_document' for #<Event:0x007fb5fa291780>

my Event model:
```ruby
class Event < ActiveRecord::Base
  include FriendlyIdAble
  include PgSearch
  pg_search_scope :search_by_name, against: :name
  
end
```
I'm using pg_search 1.0.4

**Comment by folivi** [comment]
hi,
any news about this?

**Comment by folivi** [comment]
Hi,
after digging, I found out the issue my not be related to pg_search as I updated my globalize gem to a newer version where the :name column is moved to the translations table.
The translation table had to be added as associated against:
`ruby
associated_against: {event_translations: [:name, :description],
`

**Comment by nertzy** [comment]
Oh I see what you're asking now.

`pg_search_scope` doesn't use a separate index. It searches the database table for your model directly. So there is no need to re-index anything. Any row in your `events` table that matches the query should be returned.
