### ISSUE TITLE
Quick question: which model attribute contains the search term?

### ISSUE THREAD

**Issue by osetinsky** [Casecommons/pg_search#255]
Hey everyone, I asked this question on SO but haven't received any answers:

https://stackoverflow.com/questions/31302140/rails-pg-search-which-model-attribute-contained-the-search-term

For scoped search, I'd like to know which of the model's attributes set pg_search_scope contain the relevant search terms if any. I've been scouring the forums but can't find the answer. Thanks!

**Comment by nertzy** [comment]
There's no automatic way to figure that out. You'd need to roll your own solution. PostgreSQL doesn't have any functions we could call to get that information as of now.

Grant Hutchins

**Comment by osetinsky** [comment]
Ok, thanks Grant! Appreciate your work on pg_search

**Comment by rubentrf** [comment]
Maybe there's a way to insert the key that matched the terms into the "pg_search_documents" table so making a "multisearch" will return a ::Document object that contains that info?
