### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by TiteiKo** [Casecommons/pg_search#257]
On the update from https://github.com/Casecommons/pg_search/compare/v1.0.3...v1.0.4, I suddenly get this on all my pg_search_scope : 

```
NoMethodError: undefined method `[]' for nil:NilClass
from [...]/gems/pg_search-1.0.4/lib/pg_search/features/tsearch.rb:14:in `initialize'
```

I have no idea how to reproduce it as it **doesn't happen on a clean project** (same postgres, rails, pg_search, arel and pg versions)

* no other gem was updated at the same time
* I get that error whatever params I put in, from the simplest pg_search_scope :test, against: :name to a full lenght scope with search against and prefixes
* Hell I even get it when using a trigram search :confused: 

This issue is really vague, and I know how frustrating an issue like that feels, but if you've stumbled on it at some point or have any idea of how I could get that... any insights would be welcomed...

**Comment by nertzy** [comment]
Does this still happen on v1.0.5, which was released yesterday?

**Comment by TiteiKo** [comment]
Sorry, didn't see the question

Yes it does still with v1.0.5

**Comment by kplawver** [comment]
I found where the bug gets triggered, but not necessarily its source, but I have a pull requests that allows it to work through the bug and still return results (though it looks like it might be ignoring some `pg_search_scope` options, like dictionary).

**Comment by kplawver** [comment]
@TiteiKo I'm going to close my pull request because it doesn't actually fix anything, but I'm running into the same thing and I'm trying to narrow down the culprits.  Does the app the doesn't work happen to be using ActiveAdmin and/or Ransack?  If so, I think we might have our culprit (still not sure exactly where in either of them, but those are my primary suspects at the moment).

**Comment by TiteiKo** [comment]
@kplawver Nope, the app doesn't use ActiveAdmin nor Ransack (dependencies included)...
Can you send me your Gemfile.lock so I can compare it to mine and see the common gems ?

**Comment by TiteiKo** [comment]
Ok, so I copied my gemfile & gemfile.lock to a new project, plugged to the same database, copied and dried a model, updated pg_search and then removed gems to find my culprit

So, mine is the mongo gem, which makes no sense as it is non invasive on models

How to reproduce:

```
rails new testPgSearch
rails g model Sample name:string
```

Content of Gemfile :

```ruby
source 'https://rubygems.org'

gem 'rails'

gem 'pg'
gem 'pg_search'

gem 'mongo'
gem 'bson_ext'  # not required to reproduce, still fails without, but add a big warning
```

Content of models/sample.rb

```ruby
class Sample < ActiveRecord::Base
  include PgSearch
  pg_search_scope :query,
                  against:  :name
end
```

Then just bundle install/update, db:create & migrate and run in the console:

```ruby
Sample.query('foo')
```

**Comment by kplawver** [comment]
That's some excellent sleuthing.  I've also got mongo in my Gemfile.  Now to figure out what it's doing to cause this...

**Comment by kplawver** [comment]
Found it!  https://github.com/mongodb/mongo-ruby-driver/blob/1.x-stable/lib/mongo/utils/core_ext.rb#L27-L35

I was able to get pg_search working by adding this in an initializer:

```
class Hash
  def assert_valid_keys(*valid_keys)
    valid_keys.flatten!
    each_key do |k|
      unless valid_keys.include?(k)
        raise ArgumentError.new("Unknown key: #{k.inspect}. Valid keys are: #{valid_keys.map(&:inspect).join(', ')}")
      end
    end
  end
end
```

(which is the original Rails 4 version of `assert_valid_keys`)

**Comment by amarshall** [comment]
@kplawver You could also probably fix it by requiring `mongo` before `active_support`. Though it may be worth pull-requesting a change to mongo-ruby-driver to wrap that method definition in a `unless {}.respond_to?(:assert_valid_keys)`.

I don’t think there’s really much that we can do about this aside from not using ActiveSupport’s `assert_valid_keys` (seems silly since we rely on ActiveRecord already anyway), as it’s really an issue with multiple libraries monkey-patching the same thing.

**Comment by TiteiKo** [comment]
@amarshall wow hadn't seen that my version of the gem was so outdated! A bundle update was not updating it (because of dependencies between mongo and bson_ext)

Made an issue on mongo's jira => https://jira.mongodb.org/browse/RUBY-1066 
https://github.com/TiteiKo/mongo-ruby-driver/commits/RUBY-1066
The fix is pretty straightforward but I can't seem to launch the tests so I'm not sure it hasn't broke stuff for mongo

**Comment by TiteiKo** [comment]
As this is not a pg_search issue, I'm closing this thread.
Thanks a lot @amarshall and @kplawver for your really useful inputs


For anyone who'd stumble upon this:

* I hope it will be fixed with the next minor version of mongo 1.x (1.12.4)
* in the meantime, you can use the branch RUBY-1066 on my fork
* or just upgrade to mongo 2.x
