### ISSUE TITLE
How to search from beginning of a string 'abc%'

### ISSUE THREAD

**Issue by phlegx** [Casecommons/pg_search#261]
How can I search with pg_search on a column (e.g. name) starting from the first char and with a wildcard parameter.

**Example**

names: "Tom Tailor", "Tom Tilman"
search: LIKE 'Tom T%'

**Comment by nertzy** [comment]
Please refer to the README section about `:prefix`

https://github.com/Casecommons/pg_search#prefix-postgresql-84-and-newer-only
