### ISSUE TITLE
Scopes cannot be chained – specify aliases

### ISSUE THREAD

**Issue by tyre** [Casecommons/pg_search#263]
If I have multiple search scopes and attempt to chain them, I get a conflict in the table aliases. They are all set to `pg_search`, so that's sad.

What if we included an alias option to specify?
```ruby
class Address < ActiveRecord::Base
  pg_search_scope :search_by_street, against: :street,
    using: {
      tsearch: {
        dictionary: 'english',
        prefix: true,
        tsvector_column: 'street_tsv'
      }
    },
    alias: "addresses_search_by_street"

  pg_search_scope :search_by_street_2, against: :street_2,
    using: {
      tsearch: {
        dictionary: 'english',
        prefix: true,
        tsvector_column: 'street_2_tsv'
      }
    },
    alias: "addresses_search_by_street_2"
end
```

**Comment by nertzy** [comment]
What version are you using? Version 1.0.5, which I released earlier today, makes some changes to how aliases are generated.

**Comment by tyre** [comment]
Wow, how fortuitous! Upgraded to 1.0.5 and it now aliases tables with hashes.

Thanks @nertzy

**Comment by nertzy** [comment]
Awesome, great timing! :)
