### ISSUE TITLE
any way to use a custom configuration from pg_search?

### ISSUE THREAD

**Issue by garbo999** [Casecommons/pg_search#268]
I have a full text configuration called "public.testcfg":

```
postgres=# \dF
               List of text search configurations
   Schema   |    Name    |              Description              
------------+------------+---------------------------------------
 pg_catalog | english    | configuration for english language
 ...
 pg_catalog | simple     | simple configuration
 ...
 public     | testcfg    | 
(18 rows)
```

It looks like this (and note that it uses the extension `public.testparser`).

```
postgres=# \dF+ testcfg
Text search configuration "public.testcfg"
Parser: "public.testparser"
 Token | Dictionaries 
-------+--------------
 word  | english_stem
```

Question: Is there any way to use this from pg_search? I can't figure it out.

**Comment by Miratan** [comment]
I'm having the same issue. Did you find a solution?

**Comment by garbo999** [comment]
No, I couldn't figure anything out. My conclusion was that pg_search is unable to do this. I think the Sunspot gem would be a good alternative (supports stemming).

**Comment by nertzy** [comment]
I'm pretty sure you can use your configuration by passing it as the (unfortunately incorrectly-named) `:dictionary` argument to `:tsearch`.
