### ISSUE TITLE
Multi tenant application scope.

### ISSUE THREAD

**Issue by holden** [Casecommons/pg_search#281]
I have an application which has multiple organizations (or applications) and I would like to filter/scope the results of a multisearch by the current organization.

So far the best I've come up with is to build a method in the organization class to which scopes the multisearch, is there a faster/more robust approach?

(Each model I'm search has an organization method)

### class Organization

    def search(term)
      result = []
      PgSearch.multisearch(term).eager_load(:searchable).find_each do |record|
        if record.searchable.organization == self
          result << record
        end
      end
      return result
    end

**Comment by nertzy** [comment]
One approach might be to reopen the `PgSearch::Document` model and add `belongs_to :organization` to it, along with the corresponding migration on `pg_search_documents`. You would also need to add some code (perhaps in `before_validate`) to copy the organization ID from the searchable model to the search document record.

At that point, because `PgSearch.multisearch` simply returns a scope of `PgSearch::Document`, you'd be able to do something like:

```ruby
PgSearch.multisearch("foo").where(organization_id: some_organization.id)
```

Alternatively, it may be possible to create a view that queries `pg_search_documents` and does various joins to bring in the organization IDs from the other tables.

Feel free to ask follow-up questions here as you develop a solution for your use case.

**Comment by thewoolleyman** [comment]
FYI - I got this working, scoped to an "account_id" multitenant field.  I also had to modify the rebuild sql. Here's the diff to help anyone else trying to do the same.  **NOTE: this is only tested with multisearch in a basic barebones tsearch config**.:

```diff
diff --git a/config/initializers/pg_search_multitenant_patch.rb b/config/initializers/pg_search_multitenant_patch.rb
new file mode 100644
index 000000000..f46b0017e
--- /dev/null
+++ b/config/initializers/pg_search_multitenant_patch.rb
@@ -0,0 +1,29 @@
+# based on https://github.com/Casecommons/pg_search/issues/281#issuecomment-185723700
+module PgSearch
+  class Document < ActiveRecord::Base
+    belongs_to :account
+
+    before_save do |record|
+      record.account_id = searchable.account_id
+    end
+  end
+
+  module Multisearch
+    class Rebuilder
+      def rebuild_sql_template
+        <<-SQL.strip_heredoc
+          INSERT INTO :documents_table (searchable_type, searchable_id, account_id, content, created_at, updated_at)
+            SELECT :base_model_name AS searchable_type,
+                   :model_table.#{primary_key} AS searchable_id,
+                   :model_table.account_id AS account_id,
+                   (
+                     :content_expressions
+                   ) AS content,
+                   :current_time AS created_at,
+                   :current_time AS updated_at
+            FROM :model_table :sti_clause
+        SQL
+      end
+    end
+  end
+end
diff --git a/db/migrate/20170710002738_create_pg_search_documents.rb b/db/migrate/20170710002738_create_pg_search_documents.rb
index b5cd588a2..2447dbf35 100644
--- a/db/migrate/20170710002738_create_pg_search_documents.rb
+++ b/db/migrate/20170710002738_create_pg_search_documents.rb
@@ -4,6 +4,7 @@ class CreatePgSearchDocuments < ActiveRecord::Migration
       create_table :pg_search_documents do |t|
         t.text :content
         t.belongs_to :searchable, :polymorphic => true, :index => true
+        t.belongs_to :account, index: true
         t.timestamps null: false
       end
     end
diff --git a/db/schema.rb b/db/schema.rb
index 4cab9775d..3de55ff9f 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -839,8 +839,10 @@ ActiveRecord::Schema.define(version: 20170710002738) do
     t.text     "content"
     t.string   "searchable_type"
     t.integer  "searchable_id"
+    t.integer  "account_id"
     t.datetime "created_at",      null: false
     t.datetime "updated_at",      null: false
+    t.index ["account_id"], name: "index_pg_search_documents_on_account_id", using: :btree
     t.index ["searchable_type", "searchable_id"], name: "index_pg_search_documents_on_searchable_type_and_searchable_id", using: :btree
   end
 

```
