### ISSUE TITLE
"Can't modify frozen hash" after search_document deletion

### ISSUE THREAD

**Issue by ksol** [Casecommons/pg_search#282]
Hello,

while trying to debug an issue on a rails app, I found what I think is a bug. The stack: ruby 2.2.3 Rails, 4.2.5, pg_search 1.0.5, using multisearch. The steps to reproduce are easy:
1. Load a model that is multisearchable (`@user = User.last`)
2. Save this model, which will insert/update the search document (`@user.save`)
3. Destroy the search document (`@user.pg_search_document.destroy`)
4. Try to save the model again (`@user.save`)

And that's where it happens : 

```
RuntimeError: Can't modify frozen hash
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/attribute_set/builder.rb:45:in `[]='
```

Reloading the user (`@user = User.find @user.id`) and saving it again causes no problem.

I hope there is enough information to help! Thanks for your time

**Comment by nertzy** [comment]
That makes sense. I assume that `@user.pg_search_document` gets marked as deleted but the reference sticks around.

Does calling `@user.destroy_pg_search_document` give different results?

**Comment by ksol** [comment]
> Does calling @user.destroy_pg_search_document give different results?

it raises a `NoMethodError: undefined method 'destroy_pg_search_document' for #<User:0x007ff2b3be84c8>`

**Comment by nertzy** [comment]
Oh I thought that the association would provide that method by default. I'll look closer at this soon.

Grant Hutchins
