### ISSUE TITLE
Can pg_search be used for faceted search and is there an example?

### ISSUE THREAD

**Issue by rubytastic** [Casecommons/pg_search#284]
Can pg_search be used for faceted search and is there an example?
Already searched online for long time. 

Since its low on memory I would like to use pg_search to build relative simple faceted search UI with result page. Some guidance in this direction or an example that demonstrates would be great.

**Comment by nertzy** [comment]
Yes, you can do faceted search with pg_search. I don't have a good example handy.

Facets are essentially scopes.

Let's say you want to limit your search to people who live in Texas. If you can create a scope like this:

```ruby
Person.in_state("TX")
```

and a search scope like this:

```ruby
Person.named("Sally")
```

Then you can chain the two and get a faceted result:

```ruby
Person.named("Sally").in_state("TX")
```

Essentially it's pg_search's job to do the text search, and other scopes' job to filter the results. And the programmer's job to figure out some way to hook it all together into a UI. So nothing automatic.
