### ISSUE TITLE
pg_search with Arabic, Japanese and Chinese

### ISSUE THREAD

**Issue by moeabdol** [Casecommons/pg_search#287]
I can't seem to get pg_search working with non-latin languages.
I have an activerecord model
```
class Car < ActiveRecord::Base
  include PgSearch
  multisearch against: [:en_name, :ar_name, :jp_name, :ch_name], using: [:tsearch, :trigram], ignoring: :accents
end
```
In rails console I create a Car record
```
toyota = Car.new(en_name: "toyota", ar_name: "تويوتا", jp_name: "トヨタ", ch_name: "丰田")
toyota.save
```
Now if I search for the record using an english keyword it works
`PgSearch.multisearch("toyota") #=> [#<PgSearch::Document searchable: toyota>]`
But if I search with arabic, japanese, or chines keywords I get nothing
```
PgSearch.multisearch("تويوتا") #=> []
PgSearch.multisearch("トヨタ") #=> []
PgSearch.multisearch("丰田") #=> []
```
Can anyone please point me to how I can implement full-text search using pg_search on no-latin languages. Thanks.

**Note:**
I tried a select query directly in psql
`# select * from cars where ar_name='تويوتا';`
and it works fine!

**Comment by moeabdol** [comment]
I figured out that non-latin languages will work only if you install postgresql-contrib package on Ubuntu.

I still didn't figure out how to install postgresql-contrib on osx.

**Comment by nertzy** [comment]
The `:dictionary` option for tsearch controls how the strings are parsed, and thus how they are matched to search queries. You can read more about this at https://github.com/Casecommons/pg_search/#dictionary.

Also, you can learn more about the various dictionary options in PostgreSQL at http://www.postgresql.org/docs/current/static/textsearch-dictionaries.html

The `simple` dictionary would be your best bet if you want one search scope to match multiple languages, although I'm not sure how well it supports non-Latin alphabets.
