### ISSUE TITLE
Multiple dictionaries for search scopes?

### ISSUE THREAD

**Issue by dideler** [Casecommons/pg_search#290]
When using search scopes, is it possible to configure _a list of dictionaries_ to be used? For example (this doesn't work, just for demonstration)

``` ruby
pg_search_scope ..., using: { tsearch: { dictionary: ['english', 'simple'] } }
```

For more context, see http://www.postgresql.org/docs/9.2/static/textsearch-dictionaries.html

The example they give is

``` sql
ALTER TEXT SEARCH CONFIGURATION astro_en
    ADD MAPPING FOR asciiword WITH astrosyn, english_ispell, english_stem;
```

**Comment by ktaras** [comment]
I guess it doesn't depend on the gem, but only on your available text search configurations. So you can create your own and use it.

```
CREATE TEXT SEARCH CONFIGURATION my_cool_configuration;
ALTER TEXT SEARCH CONFIGURATION my_cool_configuration ADD MAPPING FOR asciihword WITH astrosyn, english_ispell, english_stem;
```
and then in your model
```
pg_search_scope ..., using: { tsearch: { dictionary: 'my_cool_configuration' } }
```

**Comment by nertzy** [comment]
@ktaras is right. pg_search never itself creates a `TEXT SEARCH CONFIGURATION`, so that's up to you. All the gem does is pass the given name to the various functions called in the SQL it generates.
