### ISSUE TITLE
Where to put tsvector indexing columns in multisearchable?

### ISSUE THREAD

**Issue by umerfarooq** [Casecommons/pg_search#300]
Multi Search is quite slow for me with record set of just over 125k. I am trying to pre-index the content by adding tsvector columns, however trying to understand where exactly should I put the indexing columns. Ideally the columns (separate for demetaphone and tsearch) should be added in to pg_search_documents table, but it doesn't seem to work.

Any quick suggestion.

**Comment by nertzy** [comment]
I would follow this advice in our wiki. Please feel free to edit it if you have any tips or tricks.

https://github.com/Casecommons/pg_search/wiki/Building-indexes
