### ISSUE TITLE
searching deeper than one association

### ISSUE THREAD

**Issue by victorhazbun87** [Casecommons/pg_search#306]
```
  pg_search_scope :full_text_search, against: [:confirmation_code, :reference_number, :starts_at, :category, :load_category],
  using: {tsearch: {dictionary: "english"}},
  associated_against: {company_friendship: {company_friend: :name}, carrier: :name, broker: :name},
  ignoring: :accents
```

How to search through company_friendship which has one company_friend which has a name? Is this gonna be supported in the future?

**Comment by nertzy** [comment]
You could possibly do this by adding a [`has_one :through` association](http://guides.rubyonrails.org/association_basics.html#the-has-one-through-association) for the company_friend.
