### ISSUE TITLE
Feature request: scoped multisearch

### ISSUE THREAD

**Issue by classyPimp** [Casecommons/pg_search#318]
Is it possible to add scopes to multisearch (create different ft tables in config besides pg_search_documents)?
add some generators like g migration multisearch_table some_other_pg_search_table
in model `multisearchable {pg_search_table: :some_other_pg_search_table} `.
User.multisearch(pg_search_table: :some_search_table).

**Comment by transoceanic2000** [comment]
Not sure why you want different tables for the scope. I would like to be able to store a scope column in the pg_search_documents table that I can then query with a `.where` clause after the search.

Use case:
I have lots of objects I want to search of different classes, but all relating to airlines (so aircraft, routes, flights, staff, ...) When within the context of an airline I'd like to be able to restrict search results to just those relevant to that airline, but currently I have to retrieve all search results and then exclude irrelevant ones in RoR, which is inefficient. Being able to duplicate the airline_id attribute that each of the objects has into the `pg_search_documents` table would allow me to use a `.where` clause and be much more efficient.

**Comment by transoceanic2000** [comment]
Okay, just realised that the `additional_attributes` added in 1.0.6 gives me what I need, should have read the pull request in the first place.

**Comment by ryanbarkley** [comment]
@transoceanic2000 Did you get the additional_attributes option working? I couldn't find documentation on usage and can't get it to work. I created the database table but it doesn't seem to be updated when I rebuild the index.

**Comment by ryanbarkley** [comment]
If anyone else is having trouble with this, it appears that the PgSearch::Multisearch.rebuild(Product) method doesn't update the additional_attributes fields. To update them, you have to call the format of PgSearch::Document.delete_all(:searchable_type => "Product") and then call Product.find_each { |record| record.update_pg_search_document }

**Comment by classyPimp** [comment]
Closing issue. After working on the ways to implement feature, came to conclusion that it is unnecessary and will not help where special customization needed (easier to build separate tables with tsvector columns and fill them manually, while using pg_search on them as ts queries builder).
