### ISSUE TITLE
"if" keyword removed from pg_search_scope

### ISSUE THREAD

**Issue by teaearlgraycold** [Casecommons/pg_search#326]
I have a rails app that I recently updated to rails 5, and I've updated pg_search in the process.

However, now I receive this error:

```
*** ArgumentError Exception: Unknown key: :if. Valid keys are: :against, :ranked_by, :ignoring, :using, :query, :associated_against, :order_within_rank
```

This is the corresponding code in the model:

```Ruby
pg_search_scope :search, against: [:applicant_first, :applicant_last, :address],
    using: {
      tsearch: {prefix: true}
    }, :if => lambda {|import| !(import.archived?) }
```

If the `if` keyword was removed, is there an alternative? It seems to still work with the multisearchable functionality, interestingly.

**Comment by nertzy** [comment]
`if` was never available for `pg_search_scope`.

You ought to make another scope that only returns non-archived records and then chain it:

```ruby
class MyClass
  pg_search_scope :search, against: [:applicant_first, :applicant_last, :address],
    using: {
      tsearch: {prefix: true}
    }
  scope :not_archived, where(archived: false)
end

MyClass.search("some query").not_archived
```

The reason that `if` was added to `multisearchable` is so that not every record would generate a corresponding entry in the global `PgSearch::Document`'s table.

**Comment by teaearlgraycold** [comment]
Huh. I'll have to figure out what happened, then - and how that code got
into production. Thanks.
