### ISSUE TITLE
Per page limit is not working

### ISSUE THREAD

**Issue by ahmedMd** [Casecommons/pg_search#329]
Hi,

Below is my code. it display all my result on first page and ignore per_page limit. I am using will_paginate for pagination.

@search_results = PgSearch.multisearch(params[:q])
@search_results = @search_results.paginate(:page => params[:page], :per_page => 30)

Thanks in advance for help.

**Comment by nertzy** [comment]
Could you share the SQL that is generated?

**Comment by nertzy** [comment]
Closing due to lack of information. Please reopen if you have more details.
