### ISSUE TITLE
Question: Partial match

### ISSUE THREAD

**Issue by olimart** [Casecommons/pg_search#333]
Hi,

I'm trying to search for partial match against rather long stings. Just wondering whether the following scenario is supposed to work or if it's too much.

```
s = "f66612929425511aff79e4b90d835924655ec80abd6bbed8d638997e26f80f0"
ss = "e4b90d835924655e"

PgSearch.multisearch(ss)
  PgSearch::Document Load (3.3ms)  SELECT "pg_search_documents".* FROM "pg_search_documents" INNER JOIN (SELECT "pg_search_documents"."id" AS pg_search_id, (ts_rank((to_tsvector('simple', unaccent(coalesce("pg_search_documents"."content"::text, '')))), (to_tsquery('simple', ''' ' || unaccent('e4b90d835924655e') || ' ''' || ':*')), 0)) AS rank FROM "pg_search_documents" WHERE (((to_tsvector('simple', unaccent(coalesce("pg_search_documents"."content"::text, '')))) @@ (to_tsquery('simple', ''' ' || unaccent('e4b90d835924655e') || ' ''' || ':*'))))) AS pg_search_ce9b9dd18c5c0023f2116f ON "pg_search_documents"."id" = pg_search_ce9b9dd18c5c0023f2116f.pg_search_id ORDER BY pg_search_ce9b9dd18c5c0023f2116f.rank DESC, "pg_search_documents"."id" ASC
=> #<ActiveRecord::Relation []>
```

Partial match works when searching by the first characters of the string but not with text within the string.

Reading about multi_Search options I've set up the following options in an initializer.

```
PgSearch.multisearch_options = {
  using: { tsearch: { prefix: true } }
}
```

**Comment by olimart** [comment]
Closing since found out that search does not support partial match and `tsearch: {index: true}}` search only against the beginning of the string.

#44 was helpful.

**Comment by nertzy** [comment]
You want [trigram search](https://github.com/Casecommons/pg_search#trigram-trigram-search) which matches substrings.
