### ISSUE TITLE
Fix Rails 5 belongs_to behaviour override

### ISSUE THREAD

**Issue by pablocrivella** [Casecommons/pg_search#337]
The current version breaks new Rails 5 belongs_to behaviour.
Some explanations [here](https://github.com/plataformatec/devise/commit/c2c74b0) and [here](https://github.com/rails/rails/issues/23589#issuecomment-228207292)

**Comment by lleger** [comment]
I think my PR #322 should fix this. A new version hasn’t been released yet but you can point to master to get the fix.

**Comment by nertzy** [comment]
v2.1.0 and later should contain the fix now.
