### ISSUE TITLE
Faceted search with per-facet results count

### ISSUE THREAD

**Issue by diguliu** [Casecommons/pg_search#338]
This is actually a call for help in order to figure out if it's really possible to solve this problem using pg_search (which would be lovely!). I've looked all of the place but couldn't find any answer to this.

I want to build a search page that displays multiple facet types for the user to filter his results. Pg_search solves this problem easily just by chaining multiple scopes. Piece of pie. But I would like to display only the facets options that actually have any results matching the query string and the already applied facets. It would be even better to be able to display the number of results available on each facet option.

Check this image as an example of what I want to do. This is a search for a guitar where there are 3 facet types each one with multiple options and the results count:

![facet-filter](https://cloud.githubusercontent.com/assets/114025/20407253/4ee70e14-acef-11e6-8312-0e3d20078489.png)

I don't know if pg_search has any support for this kind of information and iterate through each facet option to calculate the number of results seems like a performance disaster. I really don't  want to use any specific full-text search engine like Solr or Sphinx only for this feature. In the worst case scenario I'm considering doing this through raw dynamic SQL but that's something I'm avoiding as well.

Any suggestions?

**Comment by nertzy** [comment]
I'm guessing that it's possible by chaining `.count`. and `.group_by` in the right way. pg_search doesn't do anything here beyond what you'd be able to do with any other scope, so I'm going to close this issue.
