### ISSUE TITLE
pg_search_scope in model but rake/console commands will not let me rebuild

### ISSUE THREAD

**Issue by eUstundag** [Casecommons/pg_search#340]
Current specs
Rails version             4.2.6
Ruby version              2.3.0-p0 (x86_64-darwin15)
RubyGems version          2.6.8
Rack version              1.6.4

in gemfile:
gem 'pg', '~> 0.15'

in model:
  include PgSearch

  pg_search_scope :search_refs, :against => [:title, :description,:document_file_name]

when i run in terminal: rake pg_search:multisearch:rebuild[ReferenceLink]
or in console: PgSearch::Multisearch.rebuild(ReferenceLink)

PgSearch::Multisearch::ModelNotMultisearchable: ReferenceLink is not multisearchable. See PgSearch::ClassMethods#multisearchable

I created a new dummy record for this model and i was able to search for title, description and document_file_name so my issue lies within getting this model to update with the current records in the database

any ideas?

**Comment by nertzy** [comment]
When you use `pg_search_scope`, there is no separate table to rebuild.

It's when you use `multisearchable` that you have a separate table.

**Comment by eUstundag** [comment]
I understand that as I've read the documentation several times. The previous created records are not found when I attempt to call the search method on the class. ReferenceLink.search_refs ('a') returns nothing.

**Comment by nertzy** [comment]
In English, "a" is a stopword, meaning that it is filtered out of searches. You may want to use `prefix: true` or `dictionary: "simple"` if you want a search with `"a"` to return results.
