### ISSUE TITLE
Question: Return User with only the matching associated objects

### ISSUE THREAD

**Issue by genericlady** [Casecommons/pg_search#346]
Let's say we have a `User` model with a has_many relationship to `Location`. If I query someone named George that has two locations is it possible to get back only the matched location when using associated_against?

**Comment by nertzy** [comment]
You can chain search scopes onto associations, just like any other Active Record scope.

```ruby
user = User.find_by_name("George")
locations = user.locations.search("Tahiti")
```

A good rule of thumb is that you can use a search scope in generally the same ways you would use code similar to `where(title: "Some Title")`

**Comment by genericlady** [comment]
That seems too costly for an entire collection. I decided to just map a new collection of locations from the results and use that for the thing i needed to do. Thank you for replying.

**Comment by nertzy** [comment]
@genericlady you should look at the log output to see what SQL is generated. 

Active Record scopes do not generate a query until they are iterated. So my query above does not load all locations, it only loads the locations that match the search.

So even though it looks like it will query for every record, it actually doesn't in practice.

See [this Rails guide](http://guides.rubyonrails.org/active_record_querying.html#understanding-the-method-chaining) for more details.

Hope this helps!
