### ISSUE TITLE
Search by part of word

### ISSUE THREAD

**Issue by rusikf** [Casecommons/pg_search#351]
Hello ruby hackers

Let's we have 
```ruby
# console
News.create(url: 'http://www.cbssports.com/index.html')
```
```ruby
# model
include PgSearch
pg_search_scope :pg_search, using: { tsearch: { prefix: true } }, against: [:url]
```
```ruby
News.pg_search('sport') # => no results, why ?
News.where('url LIKE :q', { q: 'sport' }) # valid results
```
**Question**: It looks, that tsearch doesn't search part of phrases, only words??
_If I update url to 'sport 123' I get valid results but I need search by part, as on example 'sport' Also I need english dictionary and weight, so it looks I can't use trigram?_

**Comment by karensg** [comment]
`prefix` means that the word has to start with it. You should use `tsearch`

**Comment by nertzy** [comment]
`tsearch` would usually consider cbssports to be the full word, so prefix would only match queries starting with "cbs...". I think @karensg meant to suggest `trigram` search, which finds substrings and even allows for some misspellings.
