### ISSUE TITLE
Include a standard "ILIKE" search

### ISSUE THREAD

**Issue by djsegal** [Casecommons/pg_search#356]
Currently something like:

```
@core_query.where \
          "name ILIKE ?", "%#{ search_param }%"
```

will catch some values not found by:

+ tsearch
+ trigram
+ dmetaphone

**Comment by tostrio** [comment]
Would also like this. `pg_search` is super readable and easy to use compared to other association-search-solutions.

**Comment by nertzy** [comment]
Duplicate of #3
