### ISSUE TITLE
Empty search in multisearch

### ISSUE THREAD

**Issue by mei33** [Casecommons/pg_search#357]
According to https://github.com/Casecommons/pg_search/issues/49 there is simple way to prevent user from searching empty query:

```
class MyModel < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search_by_name, :against => :name

  def self.search(query)
    if query.present?
      search_by_name(query)
    else
      # No query? Return all records, newest first.
      order("created_at DESC")
    end
  end
end
```

But what about Multisearch? I tried use something like that:
```
class Event < ActiveRecord::Base

  include PgSearch

  def self.multisearch(query)
    if query.present?
      multisearch(query)
    else
      flash.now[:notice] = "Your search is empty!"
    end
  end

  multisearchable against: [:title, :subtitle]

  after_save :reindex

private

  def reindex
    PgSearch::Multisearch.rebuild(Event)
  end
```
But it didn't work out. Maybe I'm missing some little bug like a dot or comma, maybe there is bigger mistake. Any ideas?

**Comment by nertzy** [comment]
You want to call `PgSearch.multisearch` if query is present. Your code as shown will repeatedly call `Event.multisearch` and thus recurse infinitely.
