### ISSUE TITLE
index pg_search_scope

### ISSUE THREAD

**Issue by nqtien310** [Casecommons/pg_search#358]
Context: I'm using Rails 3 and have a huge `users` table which usually take like 10 minutes for a search query.  So I decided to integrate PgSearch
````
class User < ActiveRecord::Base
  include Concerns::XmlTagger
  pg_search_scope :qsearch, :against => [:email, :first_name, :last_name]
end
````

But the performance doesn't change. I guess it's all about creating the right indexes. But I don't see any mention of how to create index for pg_search_scope in the documentation.

Keep in mind that I wanna search agains 3 different columns in a same table, what's the right index, and how to reindex the current data.

**Comment by nertzy** [comment]
See https://github.com/Casecommons/pg_search/wiki/Building-indexes on our wiki. It's still a pretty manual process, but is possible.

**Comment by gnclmorais** [comment]
Related to this, we just found out that the index needs to be _multicolumn_, i.e., it needs to include _all_ the fields you are setting `pg_search_scope` `against` to.

**Comment by nertzy** [comment]
This article gives a deeper dive into increasing performance.

https://pganalyze.com/blog/full-text-search-ruby-rails-postgres
