### ISSUE TITLE
:fragment_delimiter option not passed into ts_headline query

### ISSUE THREAD

**Issue by ansonhoyt** [Casecommons/pg_search#360]
This gem has worked beautifully. I may have found a `highlight` option that isn't getting passed through to postgres.

The pg_search `fragment_delimiter` option corresponds to the postgres [ts_headline](https://www.postgresql.org/docs/current/static/textsearch-controls.html) `FragmentDelimiter` option.

I added this to my initializer (that is otherwise working)
```ruby
# /config/initializers/pg_search.rb
PgSearch.multisearch_options = {
  using: {
    tsearch: {
      prefix: true,
      highlight: {
        start_sel: '<mark>',
        stop_sel: '</mark>',
        max_fragments: 3,
        fragment_delimiter: "test" # <= I added this
      }
    }
  }
}
```
When I reload rails and search, I still see the default delimiter '...' in my results.

So, I checked the SQL that pg_search generates, and noticed other configured options are showing up, but not `FragmentDelimiter`:
```ruby
$ rails c
> PgSearch.multisearch('test').with_pg_search_highlight.to_sql
=> "SELECT ((ts_headline((coalesce(\"pg_search_documents\".\"content\"::text, '')), (to_tsquery('simple', ''' ' || 'test' || ' ''' || ':*')), 'StartSel = <mark>, StopSel = </mark>, MaxFragments = 3'))) AS pg_search_highlight, pg_search_documents.* FROM \"pg_search_documents\" INNER JOIN (SELECT \"pg_search_documents\".\"id\" AS pg_search_id, (ts_rank((to_tsvector('simple', coalesce(\"pg_search_documents\".\"content\"::text, ''))), (to_tsquery('simple', ''' ' || 'test' || ' ''' || ':*')), 0)) AS rank FROM \"pg_search_documents\" WHERE (((to_tsvector('simple', coalesce(\"pg_search_documents\".\"content\"::text, ''))) @@ (to_tsquery('simple', ''' ' || 'test' || ' ''' || ':*'))))) AS pg_search_ce9b9dd18c5c0023f2116f ON \"pg_search_documents\".\"id\" = pg_search_ce9b9dd18c5c0023f2116f.pg_search_id ORDER BY pg_search_ce9b9dd18c5c0023f2116f.rank DESC, \"pg_search_documents\".\"id\" ASC"
```
Likely just needs added to a list of options somewhere. Sorry I haven't put together a pull request, but I have a hot date tonight. :smile:

**Comment by nertzy** [comment]
In version 2.1.0 you can now pass all of the various options.

Note that they now need to be formatted the way that PostgreSQL expects, so you will likely want to use:

```ruby
PgSearch.multisearch_options = {
  using: {
    tsearch: {
      prefix: true,
      highlight: {
        StartSel: '<mark>',
        StopSel: '</mark>',
        MaxFragments: 3,
        FragmentDelimiter: "test"
      }
    }
  }
}
```

**Comment by ansonhoyt** [comment]
I noticed the 2.1.0 changelog mentioned ts_headline options, but hadn't had a chance to update my gems and see if that applied here. Thanks for letting me know!
