### ISSUE TITLE
Way to not rank pg_search_scope results

### ISSUE THREAD

**Issue by djsegal** [Casecommons/pg_search#363]
For example,

If I have:

```
  pg_search_scope :deep_search, against: [:name, :description]
```

this will apply an `order`ing. 

-------

I don't want that because I want to apply my own sorting dynamically. 

+ Is there a way to do this with `ranked_by`? 
+ Otherwise, how else could I accomplish this?

**Comment by nertzy** [comment]
You can chain `.unscope(:order)` to the end of a search scope and it will ignore the order.

See http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-unscope
