### ISSUE TITLE
Search with non-word characters like ?*+# in the beginning of a word using `prefix: true` option

### ISSUE THREAD

**Issue by chumakoff** [Casecommons/pg_search#364]
When there is a column with a value, having non-word characters like ?*+# in the beginning, there are two unexpected scenarios (let's take the **"!word**" value for instance):

1.  It can't be found like this `Model.search("!")`
2. It can be found like this `Model.search("word")`

I am using `using: {tsearch: {prefix: true}}` option.

The question is: **Is this behavior caused by the gem, or it is default behavior of Postgres itself ? Are there any options to change this behavior in order to consider non-word characters as normal?**

**Comment by nertzy** [comment]
PostgreSQL defines what is and isn't a word, and what parts of a word are considered when searching.

You can use the `:dictionary` option to try out different text search configurations  to see if they work better for your use case. The "simple" dictionary is designed to do minimal processing to the text input and so it might work better for your use case.
