### ISSUE TITLE
Fetching db indexes (lower and unaccent)

### ISSUE THREAD

**Issue by ribanez7** [Casecommons/pg_search#365]
In the README it says that we can use an index with a custom unaccent function and the full_text_search will look against that index. For example, my unaccented immutable function is called "**f_unaccent**".
I also have an index using this function:

```ruby
add_index :countries, 'f_unaccent(name) varchar_pattern_ops', name: 'index_country_name_unaccented'
```

So, placing in my config:

```ruby
PgSearch.unaccent_function = "f_unaccent"
```

pg_search would look against the index, which is much faster.

My question is:
Would an index that combines **lower** and **unaccent** functions be triggered by pg_search/full_text_search  ?
Or, unfortunately, it would be a useless index?

The index would be 

```sql
lower(f_unaccent(name)) varchar_pattern_ops
```

I don't know if the lower function would be usefull working with full_text_search algorithms. The docs doesn't say so much about case sensitiveness.

Many thanks!

**Comment by nertzy** [comment]
Just adding an index for `f_unaccent(name)` is unlikely to actually speed up your queries. Look at the wiki page for [Building Indexes](https://github.com/Casecommons/pg_search/wiki/Building-indexes) for more context. Unfortunately, building indexes for pg_search is still pretty complicated.

It's important to look at `EXPLAIN` plans for the queries that pg_search generates to see if any indexes are actually being used.

`lower()` never gets called by pg_search, so adding an index on that will have no effect. Case-sensitivity is something that the various dictionaries in pg_search handle. My guess is that in pretty much every case, PostgreSQL's full text search functions ignore case.
