### ISSUE TITLE
Ordering is not bringing the best ranked first

### ISSUE THREAD

**Issue by Miratan** [Casecommons/pg_search#370]
Searching for product name with 'laranja' using pg_search below, the result bring 'Mel Laranja 500g' before 'Laranja Açúcar Orgânica 1kg'. The correct result should be 'Laranja Açúcar Orgânica 1kg' before 'Mel Laranja 500g'. If the product name starts with the query it should return first.

```
pg_search_scope(
  :search,
  ignoring: :accents,
  against: %i(name),
  using: {
    tsearch: {
      dictionary: 'portuguese',
      prefix: true
    },
    trigram: {
      threshold: 0.3
    }
  }
)
```

**Comment by nertzy** [comment]
`pg_search` only generates the query, it has no direct control over the way PostgreSQL chooses to sort results.

You can pass a [`:normalization` argument](https://github.com/Casecommons/pg_search#normalization) to `tsearch` to influence how this ranking works.

**Comment by nertzy** [comment]
You can also experiment with the top-level [`:ranked-by`](https://github.com/Casecommons/pg_search#ranked_by-choosing-a-ranking-algorithm) argument, to bring in some of the `:trigram` ranking, which has some slight tendency to match the first word more highly.
