### ISSUE TITLE
How do you install the contrib packages?

### ISSUE THREAD

**Issue by kibaekr** [Casecommons/pg_search#38]
I've looked everywhere, but I can't seem to find how to install the trigram and fuzzy contrib packages. I am currently using Ubuntu 11.10 and Postgres 9.1.3 (recently updated), but I can't figure out where exactly I am supposed to type 'CREATE EXTENSION' or 'gmake install.'

These are the comments I made while I was trying to figure it out, but I don't think it works still.
#1. go here http://www.cyberciti.biz/faq/linux-installing-postgresql-database-server/
#2. enter '$ su - postgres'
#3. password is either just enter, or you can define pword by 'sudo passwd postgres'
#4. '$ psql template1'
#5. 'CREATE EXTENSION pg_trgm'
#6. 'CREATE EXTENSION fuzzystrmatch'
# cd /usr/share/postgresql/9.1/extension

**Comment by Babbz75** [comment]
For some reason the contrib package migration is not working on heroku. Does someone have a solution for this?

**Comment by nodox** [comment]
I'm having the same problems as everyone else. I performed a migration and schema.rb update but I still get 

`ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function pg_search_dmetaphone(text) does not exist`

**Comment by Babbz75** [comment]
@nodox Does you schema have these at the top:

  enable_extension "plpgsql"
  enable_extension "pg_trgm"
  enable_extension "fuzzystrmatch"

I run into this problem every time I use pg_search and quite honestly I never know what fixes it. Possibly try to do:

bundle exec rake db:schema:load 
bundle exec rake db:structure:load 

Otherwise I've also solved it by doing this:

http://stackoverflow.com/questions/40956518/pg-search-dmetaphone-not-working-after-installing-contrib-package/40956519#40956519

**Comment by nodox** [comment]
@Babbz75 Thanks for the response. I got it working using the [last comment](https://github.com/Casecommons/pg_search/issues/175#issuecomment-264067697) on issue #175 


Here is what steps I did specifically:

1) db/schema.rb -> Added these lines manually. Not sure if it'll get overridden later.
```
ActiveRecord::Schema.define(version: xxx) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "pg_trgm"
  enable_extension "fuzzystrmatch"

```

2) Created a migration to enable the extensions in postgres
```
class InstallPgPackages < ActiveRecord::Migration[5.0]
  def up
    execute "CREATE EXTENSION IF NOT EXISTS pg_trgm"
    execute "CREATE EXTENSION IF NOT EXISTS fuzzystrmatch"
  end

  def down
    execute "DROP EXTENSION IF EXISTS pg_trgm"
    execute "DROP EXTENSION IF EXISTS fuzzystrmatch"
  end
end

```

3) Created this migration which might be redundant to step 1
```
class AddPGExtensions < ActiveRecord::Migration[5.0]
  def change
    enable_extension "pg_trgm" 
    enable_extension "fuzzystrmatch"
  end
end

```

4) Ran `rails g pg_search:migration:dmetaphone` to get 
```
class AddPgSearchDmetaphoneSupportFunctions < ActiveRecord::Migration
  def self.up
    say_with_time("Adding support functions for pg_search :dmetaphone") do
      execute <<-'SQL'
CREATE OR REPLACE FUNCTION pg_search_dmetaphone(text) RETURNS text LANGUAGE SQL IMMUTABLE STRICT AS $function$
  SELECT array_to_string(ARRAY(SELECT dmetaphone(unnest(regexp_split_to_array($1, E'\\s+')))), ' ')
$function$;
      SQL
    end
  end

  def self.down
    say_with_time("Dropping support functions for pg_search :dmetaphone") do
      execute <<-'SQL'
DROP FUNCTION pg_search_dmetaphone(text);
      SQL
    end
  end
end
```

5) Reload rails server and pg server (as a counter measure)

**Comment by nertzy** [comment]
Here's our documentation for [installing PostgreSQL extensions](https://github.com/Casecommons/pg_search/wiki/Installing-PostgreSQL-Extensions).
