### ISSUE TITLE
pg_search_scope and multisearchable :against option behave differently

### ISSUE THREAD

**Issue by RossBarnie** [Casecommons/pg_search#380]
Given the following code:

```ruby
class Person < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_keyword, against: [:full_name]
  multisearchable against: [:full_name]
  
  def full_name
    "#{first_name} #{surname}"
  end
end
```

The above `search_by_keyword` fails as the `against` option specifies columns on the database record, whereas the `multisearchable` index works because the `against` option, as documented, calls each of the arguments as functions, to create the index.

To me, this is an inconsistency in the API and I would expect both to behave in the same way. Is it possible to make the single search scope use the args as function calls, rather than columns?

**Comment by RossBarnie** [comment]
I realise, having looked into this a bit more that the above is by design, so my use of the single search scope probably isn't what I want. Sorry for the noise.

**Comment by nertzy** [comment]
Thanks for the note. I think that it would probably be helpful to call out this difference better in the documentation. Maybe they shouldn’t have both been called `against`.
