### ISSUE TITLE
pg_search_rank sometimes does not have enough precision

### ISSUE THREAD

**Issue by roelbondoc** [Casecommons/pg_search#394]
I have noticed that setting a `order_within_rank` did not seem to sort correctly when some search results have a `pg_search_rank` value of `1.0`.

It turns out that the `ts_rank` function returns the data type `float4`. If I cast the return type to `float8` it reveals the hidden precision.

To display the precise `pg_search_rank` value, I am using the following workaround:

```
.select("cast(#{PgSearch::Configuration.alias('contents')}.rank as float8) as pg_search_rank_f8")
```

Is this something that should be worked into the gem itself? If anyone thinks it's worthwhile I can take a look at implementing it.

**Comment by amarshall** [comment]
PostgreSQL’s full text docs make no mention (that I can find) of gaining meaningful extra precision from coercing to a `float8`. As such, I’ve no idea if the “extra precision” is meaningful or just noise. I don’t think it’s pg_search’s place to implement undocumented/non-standard behavior—at least not by default.

You may want to open an issue with PostgreSQL itself.
