### ISSUE TITLE
Rails 6.0 support

### ISSUE THREAD

**Issue by afomera** [Casecommons/pg_search#398]
Hi all,

Looks like Rails 6.0.0.beta1 was released the other day, it also bundled in Arel into ActiveRecord.
On Rails an issue was created, https://github.com/rails/rails/issues/34983 but I believe this may fall under a gem related thing, and may require a change in the gem. 

In my application I'm upgrading for work, we use pg_search in a few models. Upon upgrading the application, we are getting errors 

```
NoMethodError: undefined method `arel_node?' for Arel:Module
/.../.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.beta1/lib/active_record/attribute_methods.rb:188:in `block in disallow_raw_sql!'
```

Based off the issue I linked from Rails, the suspicion was because the gem is adding the dependency on Arel and pulling the last released version from Rubygems (9.0.0).

Because Arel's github shows it's been moved into ActiveRecord I don't believe they're going to release a new version. Out of curiosity, I removed the dependency line from the gemspec (for Arel), and loaded my application with Rails 6.0.0.beta1 and everything seems to be working at a glance. 

This seems like it would work at face value, but I'm unsure how everyone would want to proceed, or how this would work for supporting multiple versions of ActiveRecord.

Here's what I changed for the gemspec

```diff
-  s.add_dependency 'activerecord', '>= 4.2'
-  s.add_dependency 'activesupport', '>= 4.2'
-  s.add_dependency 'arel', '>= 6'
+  s.add_dependency 'activerecord', '>= 5.2'
+  s.add_dependency 'activesupport', '>= 5.2'
```

**Comment by nertzy** [comment]
I added the explicit arel dependency when we started using a feature of arel that was available in arel 6 but not arel 5. Since Active Record 4.2 (the oldest version we support) automatically brings in arel 6, I think we can remove the arel dependency. I'm doing it right now.

**Comment by msdundar** [comment]
@nertzy Thanks! I guess you are gonna release a new version that supports Rails 6.0.0.beta1, right? When can we expect it?
