### ISSUE TITLE
How to combine Weighted Search & Association Search

### ISSUE THREAD

**Issue by kibaekr** [Casecommons/pg_search#40]
Weghted Search and Search through Associations works separately, but I was wondering how I could combine them. So I want to add the associative search as one of the weighted params.

Currently, I have 

    class Mission < ActiveRecord::Base
      include PgSearch
      pg_search_scope :search_by_weight, :against => {:title => 'B', :content => 'C'}, :using => [:tsearch] #, :trigram, :dmetaphone]
      pg_search_scope :search_by_tag, :associated_against => {
       :tags => [:name]
      }

How would I incorporate the search_by_tag as one of the weights 'A'?

**Comment by jaypinho** [comment]
Apologies if I'm misunderstanding, but shouldn't this issue be closed considering #132 has been answered?

**Comment by nertzy** [comment]
@jaypinho thanks for the helpful note. Yes, it does look like the answer to #132 applies here as well.

So, we would expect this to work:
```ruby
pg_search_scope :search_by_tag, :associated_against => {
  :tags => [{:name => 'A'}]
}
```

If this doesn't work for your use case, feel free to reopen with more information on how to reproduce the problem. Thanks!

**Comment by mattgilbertnet** [comment]
It looks like in both this issue and #132 , the conversation dropped off without anyone testing out the syntax above. When I tried syntax like that, I get this error:

`ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column events.{:name=>"B"} does not exist`

**Comment by mattgilbertnet** [comment]
I should have checked, but I'm using version 2.0.1. That's newer than the discussion above, but far from up-to-date.
