### ISSUE TITLE
Why is it necessary to include the entire PgSearch namespace?

### ISSUE THREAD

**Issue by fschwahn** [Casecommons/pg_search#408]
I'm using pg_search in a project where we namespace our models, eg. `Person`, `Person::Document`, ... Problem is with pg_search that I have to include the entire PgSearch-namespace into my model. If I now include `PgSearch` in `Person`, my `Person::Document` model gets overwritten by `PgSearch::Document`.

```ruby
class Person
  include PgSearch

  has_many :documents, class_name: "Person::Document", dependent: :destroy

  pg_search_scope :search, against: { last_name: 'A', first_name: 'B', company: 'C' }, using: { tsearch: { prefix: true } }, ignoring: :accents
end

Person.search("John") # => works as expected

Person::Document # => returns "PgSearch::Document(Table doesn't exist)", should return Person::Document
```

I fixed this by copying the relevant code (ie. the `pg_search_scope`-method) to my model, but I found myself wondering if it wouldn't be better if pg_search supplied a concern which included just the parts which are actually useful for the model to include?

**Comment by nertzy** [comment]
Thank you for pointing this out. I think that we should figure out another module that you can import that doesn't have the same problem and deprecate directly including `PgSearch`. Could you help me think of a good name for the new module?

Maybe something like `PgSearch::Model`?

**Comment by fschwahn** [comment]
`PgSearch::Model` sounds reasonable to me 👍

**Comment by fschwahn** [comment]
Awesome, thanks for the quick turnaround!
