### ISSUE TITLE
Simple trigram search does not use index

### ISSUE THREAD

**Issue by molfar** [Casecommons/pg_search#415]
I created demo app here (with seed data) https://github.com/molfar/wrong_index

I implemented basic search by trigram with word similarity. I also created GIN index for trigram. But the query, generated with pg_gem does not use gin index at all.

Is it a bug or feature? How can I make it use that index?

**Comment by nertzy** [comment]
PostgreSQL won't use an index unless it thinks it will speed up the query. Sometimes that can mean that you have to get to a pretty large dataset size before an index is used.

Is this specific to word similarity or does it also happen without word similarity? I don't know if using the `<%` operator vs the `%` operator triggers different behavior in the planner.

pg_search is responsible for the generated queries, but has no control over what PostgreSQL decides to do with the queries. So there is no possible solution from our end, unless there is a problem with the generated query. Good luck and feel free to share anything interesting you find out if you want.
