### ISSUE TITLE
Why different tsvector columns for different search methods (ex. tsearch vs. dmetaphone) if their model attrs are the same?

### ISSUE THREAD

**Issue by richiethomas** [Casecommons/pg_search#431]
I see [here](https://github.com/Casecommons/pg_search#user-content-using-tsvector-columns) that we need to implement unique tsvector columns for each search method that we use.  I'm implementing both tsearch and dmetaphone on a Listing model in a combined scope.  My scope is implemented as follows:

```
pg_search_scope(
    :search,
    against: {
      title: "A",
      description: "B",
    },
    using: {
      tsearch: {
        tsvector_column: "title_description_tsvector",
        dictionary: "english",
        any_word: true,
      },
      dmetaphone: {
        tsvector_column: "title_description_dmetaphone",
      }
    },
    ignoring: :accents,
  )
```
I know we have to create triggers for each column, so I created these two:

```
CREATE TRIGGER update_listings_tsvector_dmetaphone
    BEFORE INSERT OR UPDATE ON listings
    FOR EACH ROW
    EXECUTE PROCEDURE
    tsvector_update_trigger(
      'title_description_dmetaphone', 'pg_catalog.english', title, description
    )

CREATE TRIGGER update_listings_tsvector
    BEFORE INSERT OR UPDATE ON listings
    FOR EACH ROW
    EXECUTE PROCEDURE
    tsvector_update_trigger(
      'title_description_tsvector', 'pg_catalog.english', title, description
    )

```

Unless I'm mistaken, these triggers are exactly the same, except for the column they modify.  I think that means they populate the columns with the same data (which is borne out by the data I see for the two columns in the following instance:

```
[2] pry(main)> Listing.last
  Listing Load (0.6ms)  SELECT "listings".* FROM "listings" ORDER BY "listings"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<Listing:0x00007fbed1149438
 id: 9,
 title: "cradle foobar 2",
 description: "Here's a description for Good 8",
 title_description_tsvector: "'2':3 '8':10 'cradl':1 'descript':7 'foobar':2 'good':9",
 title_description_dmetaphone: "'2':3 '8':10 'cradl':1 'descript':7 'foobar':2 'good':9">
```

My question is, if these two triggers will always populate their columns with the same data, why do the docs say `If you want to search using multiple search methods, for example tsearch and dmetaphone, you'll need a column for each`?  Does this refer to using multiple search methods in separate scopes (as opposed to the same scope, the way I'm using it)?

**Comment by nertzy** [comment]
It's currently not well documented, sorry. You will need to create a tsvector that preprocesses the text you want to make searchable with the `pg_search_dmetaphone()` function to make it useful for a `dmetaphone` search.
