### ISSUE TITLE
need name of auto-generated pg_search_ column for select distinct order by query

### ISSUE THREAD

**Issue by sam0x17** [Casecommons/pg_search#437]
I'm getting a fairly standard `ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list` error because I am doing a distinct order by with a joins and using a pg search scope. As per https://stackoverflow.com/questions/42846286/pginvalidcolumnreference-error-for-select-distinct-order-by-expressions-mus, to fix this I just have to throw in a `.select("pg_search_...") to the chain with whatever the name of the auto-generated pg search scope is. The problem is I'm pretty sure the name changes every time. Is there a way I can get the name from the gem?

Thanks!!

**Comment by sam0x17** [comment]
So TLDR the name is not randomly generated, it is just a hash that is the same every time based on the tables involved in the query. So you can safely solve this issue by doing something like:

```
scope = scope.select('DISTINCT menus.*, pg_search_9045d6f05ca3e89ad2d6db.rank')
``

In my case

**Comment by nertzy** [comment]
Yes it should stay consistent every time.

**Comment by mockdeep** [comment]
We have been running into this, too. Tacking on the search rank seems kind of hacky, though. @nertzy is there no "blessed" way of accomplishing this? Or is this it?

**Comment by mockdeep** [comment]
Looks like tacking on a `.with_pg_search_rank` also works. That feels a lot better.

**Comment by nertzy** [comment]
Yes that is a great solution!
