### ISSUE TITLE
trigram not working for me

### ISSUE THREAD

**Issue by JohnGoodman** [Casecommons/pg_search#44]
Hey All,

I have pg_search setup and working with multi model searching. I either don't understand how trigam is supposed to work or it is not working. I installed the extensions on my postgres 9.1.3 database, but when I search for partial words, I get no response. If I search for "John" or "joh", the user with the name John is returned ( presumably from the prefix option ). I expect trigam to be able to return the same record if I search for "ohn"; however, when I do, there are no results. 

Any help figuring this out is appreciated.

Migration for installing extensions

```
class AddPgSearchFields < ActiveRecord::Migration
  def up
    execute "CREATE EXTENSION unaccent"
    execute "CREATE EXTENSION pg_trgm"
    execute "CREATE EXTENSION fuzzystrmatch"
  end

  def down
    execute "drop extension unaccent"
    execute "drop extension pg_trgm"
    execute "drop extension fuzzystrmatch"
  end
end
```

pg_search.rb

```
PgSearch.multisearch_options = {
  :using => {
    :tsearch => {:prefix => true, :any_word => true},
    :trigram => {}
  }
}
```

User.rb

```
class User < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:first_name, :last_name, :email, :direct_phone, :mobile_phone]
end
```

Company.rb

```
class Company < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:name, :email, :phone]
end
```

**Comment by Paxa** [comment]
Faced same problem, solved with retrying to search by `LIKE` if no results from trigram and tsearch:

```ruby
@places = Place.my_search(params[:q]).to_a
if @places.size < 5
  @places += Place.like_search(params[:q]).to_a
end
```

Would be nice to have as an option in `using: {ilike: {} }`

**Comment by thedanotto** [comment]
I use `multisearch` because it does a really good job of maintaining `PgSearch::Document`, which I can then do partial searches upon.

```ruby
class User
  multisearchable :against => [:first_name, :last_name, :email]
end
```

`$ PgSearch::Document.where('content like ?', "%@gmail.com%").where(searchable_type:"User")`

`PgSearch::Document.where('content like ? OR content like ?', "%@test.com%", "%dan%").where(searchable_type:"User")`

THE POSSIBILITIES ARE ENDLESS MUAHAHAHA.

**Comment by Tashows** [comment]
> I use `multisearch` because it does a really good job of maintaining `PgSearch::Document`, which I can then do partial matches upon.
> 
> ```ruby
> class User
>   multisearchable :against => [:first_name, :last_name, :email]
> end
> ```
> 
> `$ PgSearch::Document.where('content like ?', "%@gmail.com%").where(searchable_type:"User")`
> 
> OR
> 
> `$ PgSearch::Document.where('content like ? OR content like ?', "%@test.com%", "%dan%").where(searchable_type:"User")`
> 
> THE POSSIBILITIES ARE ENDLESS MUAHAHAHA.

Might be useful, however mind that it breaks additional functionality like `with_pg_search_highlight`
