### ISSUE TITLE
Scope search on enum

### ISSUE THREAD

**Issue by tabishiqbal** [Casecommons/pg_search#444]
I currently have a model with enum set as

`enum status: { open: 0, in_progress: 1, on_hold: 2, completed: 3 }`

and pg_search_scope as:

```
pg_search_scope :search_for, 
                  against: %i(title work_order_no status description),
```

however when doing a search it doesn't return any results.  Is there a way to search against enums set like above?

**Comment by vonchristian** [comment]
Chaging your enum values to string:
`enum status: { open: '0', in_progress: '1', on_hold: '2', completed: '3' }`
will work but I don't know how it might affect other parts of your application.
