### ISSUE TITLE
blog post about multi-column indexes

### ISSUE THREAD

**Issue by jjb** [Casecommons/pg_search#475]
I wrote this blog post about making multi-column indexes to cover pg_search queries

I was surprised to not find any guidance on this anywhere

maybe it would be helpful to link here from the wiki page on indexes? and/or i'm happy to inline it into the page if that's preferred.

please give me any and all feedback, thanks!

http://code.jjb.cc/how-to-create-a-multi-column-full-text-search-index-in-postgres

**Comment by nertzy** [comment]
We have a wiki page about indexes, although it's probably not the easiest thing to discover.

https://github.com/Casecommons/pg_search/wiki/Building-indexes

**Comment by jjb** [comment]
yep! that's what i was referring to re: "maybe it would be helpful to link here from the wiki page on indexes? and/or i'm happy to inline it into the page if that's preferred."

**Comment by nertzy** [comment]
That's a good point. It was intended to explain that you could have multiple columns in the expression, but it doesn't do a great job of explaining how that looks when multiple columns are involved.

If you want to expand the wiki page and/or add a link to your blog post, I think it would be completely appropriate and helpful. Thanks for leaving things better than you found them! 😄

**Comment by jjb** [comment]
cool, done https://github.com/Casecommons/pg_search/wiki/Building-indexes/_compare/467406c01d9f75c6fa1333ad23db68318ab900db...2e99589a032165dfb320b073496c60112d4cedef

my dream is to one day become a master of the whole space and revamp and expand that wiki page
