### ISSUE TITLE
add a condition to only one class while using multisearch

### ISSUE THREAD

**Issue by josh-m-sharpe** [Casecommons/pg_search#48]
I have two classes I would like to add multisearch to.  One of the classes needs an additional condition though.  I only want records where 'approved_at < now()' to be returned.  The other class does not have this requirement, but I still want to search it at the same time.

How do I fit that requirement into the call to #multisearchable such that I can still call PgSearch.multisearch('foo') which queries both classes.

Thanks!

**Comment by guilhermesimoes** [comment]
@nertzy I know it's been 4 years... But could you make this edit to your comment?

```diff
- pg_search_documents.type
+ pg_search_documents.searchable_type

- pg_search_documents.id
+ pg_search_documents.searchable_id
```

This got me stumped for a while and this edit would help other people like me :smile:

**Comment by josh-m-sharpe** [comment]
I haven't had that app running in ages, so, probably unlikely :)

**Comment by nertzy** [comment]
@guilhermesimoes Thanks!
