### ISSUE TITLE
Does this support for Multiple Databases with Active Record?

### ISSUE THREAD

**Issue by tenshiAMD** [Casecommons/pg_search#482]
Hi, I just wanna know if this supports multiple databases, read replicas, and sharding? Thank you.

References:
- https://edgeguides.rubyonrails.org/active_record_multiple_databases.html

**Comment by nertzy** [comment]
Yes, my current team uses pg_search in production with multiple databases.

**Comment by tenshiAMD** [comment]
@nertzy Hi thanks for answering this, can you elaborate more? I cannot find any documentation regarding this matter.
