### ISSUE TITLE
Rails 7 encryption column is not working with pg_search

### ISSUE THREAD

**Issue by sulmanweb** [Casecommons/pg_search#486]
I have user model:
```ruby
class User < ApplicationRecord
  include PgSearch::Model
  encrypts :email, deterministic: true

  pg_search_scope :search_user, against: { email: 'A', name: 'B' }, using: {
    tsearch: { prefix: true }
  }
```
then `User.search_user` doesn't find the user with exact email but finds with name. If I remove encryption then it works fine.

**Comment by james-em** [comment]
I believe this would be the expected behavior because the search happens at SQL level and the data is encrypted in database.

**Comment by nertzy** [comment]
Yes, there is no reasonable way to search encrypted data.

You could store a tsvector column with the text to the side of your column, but that would defeat the point of encryption.
