### ISSUE TITLE
Merging our customization into mainline?

### ISSUE THREAD

**Issue by mhenrixon** [Casecommons/pg_search#498]
Hi,

A previous developer on the project I am working on decided to fork `pg_search` personally and ended up with the following diff:

https://github.com/Casecommons/pg_search/compare/master...hldesign:pg_search:single-association-performance

I'd love to get rid of this and I have two options:

1. Monkey patch pg_search in the project directly
2. Contribute the changes (they need to be backported because we have a very old codebase with ancient dependencies).

Any interest in ts vector improvements? If so, do the changes make sense? I have no idea, I never had any issues with pg_search myself, so I can't vouch for the validity of the changes.

**Comment by nertzy** [comment]
Yes, this is pretty interesting. Please open a pull request for this!

**Comment by mhenrixon** [comment]
Opened #499 so that we can talk about it.
