### ISSUE TITLE
Request: new gem release

### ISSUE THREAD

**Issue by swrobel** [Casecommons/pg_search#530]
It has been 3 years since the last release, and fixes such as [this](https://github.com/Casecommons/pg_search/pull/487) are not in the latest gem version. Using github in my gemfile for now, but this is less than ideal.

**Comment by nertzy** [comment]
Good point. I will push a minor version soon.

**Comment by nertzy** [comment]
Still planning on doing this soon, once I get enough time to put it together. Sorry for the delay.

**Comment by swrobel** [comment]
@nertzy just a little nudge

**Comment by nertzy** [comment]
v2.3.7 is released!
