### ISSUE TITLE
Rails 7.2: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by sethaddison** [Casecommons/pg_search#536]
After upgrading from rails 7.1.3.4 to rails 7.2.0.beta1, PgSearch.multisearch generates the following error: 
`wrong number of arguments (given 2, expected 1)`

My exact code is:
`results = PgSearch.multisearch(@query).where(account_id: current_account.id)`

Works with no issue on rails 7.1x

**Comment by nertzy** [comment]
Sorry, I haven't had much time to get a release put together. I will get something out soon, especially since Active Record 7.2 is released.
