### ISSUE TITLE
LoadError (no such file to load -- pg_search/features/dmetaphone):

### ISSUE THREAD

**Issue by rmontgomery429** [Casecommons/pg_search#78]
This may very well be a Heroku issue but I thought I'd post it here in case others run into the same thing.

I'm running using their Crane database which should be Postgres 9.2.
I'm using the following: `pg_search_scope :search_by_description, :against => :description, :using => { :tsearch => {:any_word => true} }`

This works locally and has been working in the past although I recently upgraded my database to the Crane database.

The error I am receiving is "LoadError (no such file to load -- pg_search/features/dmetaphone):"

Any insights?

**Comment by giedriusr** [comment]
@rmontgomery429 is this still valid? please close the issue if not. thanks.
