### ISSUE TITLE
wrong number of arguments using dynamic search scopes

### ISSUE THREAD

**Issue by JeanOsorio** [Casecommons/pg_search#82]
I have the following search and I'm getting wrong number of arguments

pg_search_scope :advance_search, lambda {|*args, query|
      return {:against => args,
      :query => query,
      using: { tsearch: { dictionary: "spanish"} } }
  }

def self.searchadv(title, place, category)
    advance_search(:title => title, :place => place, :category => category)
end

I thinks this is an issues.

**Comment by dlinch** [comment]
@JeanOsorio I know this is from a long time ago, but I'm seeing the exact same issue. Did you ever figure out what the issue was?
