### ISSUE TITLE
multisearchable and weighting

### ISSUE THREAD

**Issue by hueezer** [Casecommons/pg_search#86]
Mulitsearch with weights don't seem to be working.

```
multisearchable :against => {:title => 'A', :description => 'B'}
```

Or is it not possible with pg_search?

**Comment by heisters** [comment]
For what it's worth, I did something similar to what @mirek and @nertzy suggest:

Create a migration like:

```
    change_table :pg_search_documents do |t|
      t.rename :content, :content_a
      t.text :content_b
      t.text :content_c
      t.text :content_d
    end
```

*After* your class calls `::multisearchable`, include the following module to override `#pg_search_document_attrs`.

```
    module OverrideInstanceMethods
      # based on PgSearch::Multisearchable#searchable_text, for overriden
      # pg_search_document_attrs below.
      def weighted_searchable_text weight
        Array(pg_search_multisearchable_options[:against])
          .select{ |symbol, w| weight.to_s.capitalize == w.to_s.capitalize || (w.nil? && weight == :a) }
          .map{ |symbol, w| send(symbol) }
          .join(' ')
      end

      def pg_search_document_attrs
        [:a,:b,:c,:d].reduce({}) do |attrs, weight|
          attrs.tap do
            attrs["content_#{weight}".to_sym] = weighted_searchable_text(weight)
          end
        end.tap do |h|
          if (attrs = pg_search_multisearchable_options[:additional_attributes])
            h.merge! attrs.to_proc.call(self)
          end
        end
      end
    end
```

Elsewhere, monkey patch PgSearch::Document to use the new columns in its search scope:

```
module PgSearch
  class Document
    # override stock Multisearchable scope
    pg_search_scope :search, lambda { |*args|
      options = if PgSearch.multisearch_options.respond_to?(:call)
                  PgSearch.multisearch_options.call(*args)
                else
                  {:query => args.first}.merge(PgSearch.multisearch_options)
                end

      {
        against: {
          content_a: 'A',
          content_b: 'B',
          content_c: 'C',
          content_d: 'D'
        }
      }.merge(options)
    }
  end
end
```

Rolling this up into a PR would be a bit more work that I can do right now, but hopefully it can provide a basis for others.

**Comment by asadakbar** [comment]
One thing to keep in mind with the above code (which is great btw), is that you will also need to implement a custom rebuild method as done here https://github.com/Casecommons/pg_search#rebuilding-search-documents-for-a-given-class (the "More sophisticated approach" example). This is because the default rebuild method assumes a single "content" column which it is rebuilding for.

**Comment by stevenm** [comment]
+1 for adding a weighting to multi column search

Id be open to requesting a pull to tackle and work through it if anyone else wanted to form a co-op to check / balance

**Comment by ericboehs** [comment]
To get weighting to work, I ended up copying the PgSearchDocument implementation to my own "SearchDocument" ActiveRecord class. It calls `pg_search_scope` against `:content` just as PgSearchDocument does. I added a tsvector column as described in the README then wrote custom rebuild methods for each AR class that I wanted multi-searchable (also in the README). The rebuild methods call `setweight` for each column (joined by `||`) as the tsvector column.

This gives me insertion-time weighting (rather than query-time weighting) but I don't stray too far from the pg_search way.

I also wrote a rake task which I run every 10 minutes to make sure my search documents are up to date (our data doesn't change often so 10 minutes if plenty fast—if we needed faster I'd add after save callbacks).

**Comment by nertzy** [comment]
If I could go back in time and do it again, I'd have written multi-search using a generator, making it easier to understand and hack on. Perhaps one day...

**Comment by jondavidjohn** [comment]
@ericboehs Any way your custom `SearchDocument` and other bits you changed could be shared with a gist?

**Comment by jondavidjohn** [comment]
I assume you'd need to change this somehow?

https://github.com/Casecommons/pg_search/blob/bc24017fd39771237094d6fd99e93a7bf9806b8d/lib/pg_search/multisearchable.rb#L11

**Comment by mengqing** [comment]
Hi @ericboehs are you able to elaborate on what you did and perhaps share some working code if possible? We're also having the same issue and is having trouble getting weighting working for multisearches. Thanks

**Comment by NemyaNation** [comment]
+1 for multisearch weighting 👍

**Comment by sobakasu** [comment]
entering @ericboehs code elaboration waiting room

**Comment by sandeepsrm21** [comment]
+1 for adding multisearch weighting :)

**Comment by DanielSBrown** [comment]
For what it's worth, I was able to get weighting to work in my project's use case. I have a small writeup with some code here: https://gist.github.com/DanielSBrown/b25dda06cff5e7c250d8b00dcf49b1be

My use case was making it so the title of multisearchable entities was prioritized higher. Here is how I accomplished that
- Add a `title` field to PgSearch::Document (in addition to our usual multisearchable field, `content`) 
- Pass the `title` into the PgSearch::Document via the `additional_attributes` key when using `multisearchable` in our resources' models
- Update our hairtrigger trigger to set our main tsvector content to be an OR of the weighted tsvector representations of our `content` and new `title` field

How that looks in practice is like this 

Trigger before the change
```ruby
    trigger.before(:insert, :update) do
      "NEW.tsv_content := to_tsvector('pg_catalog.simple', COALESCE(NEW.content, ''));"
```

Trigger after the change
```ruby
    trigger.before(:insert, :update) do
      <<-SQL
        NEW.tsv_content :=
          setweight(to_tsvector('pg_catalog.simple', COALESCE(NEW.title, '')), 'A') ||
          setweight(to_tsvector('pg_catalog.simple', COALESCE(NEW.content, '')), 'D');
      SQL
```

See the gist for more code samples of how this specific implementation worked for me
