### ISSUE TITLE
Migrating problems with pg_search to Heroku 

### ISSUE THREAD

**Issue by ayl** [Casecommons/pg_search#90]
Hey everyone,

I'm having problems with migrating an existing Rails 2.3.17 app to Heroku. It works totally fine with my custom EC2 Rails stack but on Heroku Cedar with Postgres 9.1 I can't seem to get it to work. 

In my Gemfile I have:
````ruby
gem "pg","~> 0.14.1"
gem "pg_search", "~> 0.2.1"
````

In my model I have:
````ruby
class User < ActiveRecord::Base
    include PgSearch
    pg_search_scope :search_by_full_name, :against => [:first_name, :last_name, :login] 
````

When I run it in the console:
````
ayl$ heroku run console production
Running `console production` attached to terminal... up, run.6486
Loading production environment (Rails 2.3.17)
> User.search_by_full_name("asdf")
NoMethodError: undefined method `search_by_full_name' for #<Class:0x00000004cd41b0>
	from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-2.3.17/lib/active_record/base.rb:2002:in `method_missing'
	from (irb):1
	from /usr/local/bin/irb:12:in `<main>'
````

I've been beating my head against the wall trying to figure this out to no avail... Help?

**Comment by nertzy** [comment]
Closing this out because it is old and deals with an outdated version of pg_search. Feel free to open a new issue if anything similar comes up again with the latest versions. Thanks!
